// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fish_user.p

package cn.mxz.protocols.user.fish;

public final class FishUserP {
  private FishUserP() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface FishUserProOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 freeTimes = 1;
    boolean hasFreeTimes();
    int getFreeTimes();
    
    // required .cn.mxz.protocols.user.UserBasePro user = 3;
    boolean hasUser();
    cn.mxz.protocols.user.UserBaseP.UserBasePro getUser();
    cn.mxz.protocols.user.UserBaseP.UserBaseProOrBuilder getUserOrBuilder();
    
    // required .cn.mxz.protocols.user.fish.JunketPro junket = 4;
    boolean hasJunket();
    cn.mxz.protocols.user.fish.FishUserP.JunketPro getJunket();
    cn.mxz.protocols.user.fish.FishUserP.JunketProOrBuilder getJunketOrBuilder();
  }
  public static final class FishUserPro extends
      com.google.protobuf.GeneratedMessage
      implements FishUserProOrBuilder {
    // Use FishUserPro.newBuilder() to construct.
    private FishUserPro(Builder builder) {
      super(builder);
    }
    private FishUserPro(boolean noInit) {}
    
    private static final FishUserPro defaultInstance;
    public static FishUserPro getDefaultInstance() {
      return defaultInstance;
    }
    
    @Override
	public FishUserPro getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.mxz.protocols.user.fish.FishUserP.internal_static_cn_mxz_protocols_user_fish_FishUserPro_descriptor;
    }
    
    @Override
	protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.mxz.protocols.user.fish.FishUserP.internal_static_cn_mxz_protocols_user_fish_FishUserPro_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 freeTimes = 1;
    public static final int FREETIMES_FIELD_NUMBER = 1;
    private int freeTimes_;
    @Override
	public boolean hasFreeTimes() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    @Override
	public int getFreeTimes() {
      return freeTimes_;
    }
    
    // required .cn.mxz.protocols.user.UserBasePro user = 3;
    public static final int USER_FIELD_NUMBER = 3;
    private cn.mxz.protocols.user.UserBaseP.UserBasePro user_;
    @Override
	public boolean hasUser() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    @Override
	public cn.mxz.protocols.user.UserBaseP.UserBasePro getUser() {
      return user_;
    }
    @Override
	public cn.mxz.protocols.user.UserBaseP.UserBaseProOrBuilder getUserOrBuilder() {
      return user_;
    }
    
    // required .cn.mxz.protocols.user.fish.JunketPro junket = 4;
    public static final int JUNKET_FIELD_NUMBER = 4;
    private cn.mxz.protocols.user.fish.FishUserP.JunketPro junket_;
    @Override
	public boolean hasJunket() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    @Override
	public cn.mxz.protocols.user.fish.FishUserP.JunketPro getJunket() {
      return junket_;
    }
    @Override
	public cn.mxz.protocols.user.fish.FishUserP.JunketProOrBuilder getJunketOrBuilder() {
      return junket_;
    }
    
    private void initFields() {
      freeTimes_ = 0;
      user_ = cn.mxz.protocols.user.UserBaseP.UserBasePro.getDefaultInstance();
      junket_ = cn.mxz.protocols.user.fish.FishUserP.JunketPro.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    @Override
	public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasFreeTimes()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUser()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasJunket()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getUser().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getJunket().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    @Override
	public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, freeTimes_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(3, user_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(4, junket_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    @Override
	public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, freeTimes_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, user_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, junket_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static cn.mxz.protocols.user.fish.FishUserP.FishUserPro parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static cn.mxz.protocols.user.fish.FishUserP.FishUserPro parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static cn.mxz.protocols.user.fish.FishUserP.FishUserPro parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static cn.mxz.protocols.user.fish.FishUserP.FishUserPro parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static cn.mxz.protocols.user.fish.FishUserP.FishUserPro parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static cn.mxz.protocols.user.fish.FishUserP.FishUserPro parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static cn.mxz.protocols.user.fish.FishUserP.FishUserPro parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static cn.mxz.protocols.user.fish.FishUserP.FishUserPro parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static cn.mxz.protocols.user.fish.FishUserP.FishUserPro parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static cn.mxz.protocols.user.fish.FishUserP.FishUserPro parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    @Override
	public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cn.mxz.protocols.user.fish.FishUserP.FishUserPro prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    @Override
	public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements cn.mxz.protocols.user.fish.FishUserP.FishUserProOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.mxz.protocols.user.fish.FishUserP.internal_static_cn_mxz_protocols_user_fish_FishUserPro_descriptor;
      }
      
      @Override
	protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.mxz.protocols.user.fish.FishUserP.internal_static_cn_mxz_protocols_user_fish_FishUserPro_fieldAccessorTable;
      }
      
      // Construct using cn.mxz.protocols.user.fish.FishUserP.FishUserPro.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getUserFieldBuilder();
          getJunketFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      @Override
	public Builder clear() {
        super.clear();
        freeTimes_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (userBuilder_ == null) {
          user_ = cn.mxz.protocols.user.UserBaseP.UserBasePro.getDefaultInstance();
        } else {
          userBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (junketBuilder_ == null) {
          junket_ = cn.mxz.protocols.user.fish.FishUserP.JunketPro.getDefaultInstance();
        } else {
          junketBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      @Override
	public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      @Override
	public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.mxz.protocols.user.fish.FishUserP.FishUserPro.getDescriptor();
      }
      
      @Override
	public cn.mxz.protocols.user.fish.FishUserP.FishUserPro getDefaultInstanceForType() {
        return cn.mxz.protocols.user.fish.FishUserP.FishUserPro.getDefaultInstance();
      }
      
      @Override
	public cn.mxz.protocols.user.fish.FishUserP.FishUserPro build() {
        cn.mxz.protocols.user.fish.FishUserP.FishUserPro result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private cn.mxz.protocols.user.fish.FishUserP.FishUserPro buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        cn.mxz.protocols.user.fish.FishUserP.FishUserPro result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      @Override
	public cn.mxz.protocols.user.fish.FishUserP.FishUserPro buildPartial() {
        cn.mxz.protocols.user.fish.FishUserP.FishUserPro result = new cn.mxz.protocols.user.fish.FishUserP.FishUserPro(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.freeTimes_ = freeTimes_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (userBuilder_ == null) {
          result.user_ = user_;
        } else {
          result.user_ = userBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (junketBuilder_ == null) {
          result.junket_ = junket_;
        } else {
          result.junket_ = junketBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      @Override
	public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.mxz.protocols.user.fish.FishUserP.FishUserPro) {
          return mergeFrom((cn.mxz.protocols.user.fish.FishUserP.FishUserPro)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(cn.mxz.protocols.user.fish.FishUserP.FishUserPro other) {
        if (other == cn.mxz.protocols.user.fish.FishUserP.FishUserPro.getDefaultInstance()) return this;
        if (other.hasFreeTimes()) {
          setFreeTimes(other.getFreeTimes());
        }
        if (other.hasUser()) {
          mergeUser(other.getUser());
        }
        if (other.hasJunket()) {
          mergeJunket(other.getJunket());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      @Override
	public final boolean isInitialized() {
        if (!hasFreeTimes()) {
          
          return false;
        }
        if (!hasUser()) {
          
          return false;
        }
        if (!hasJunket()) {
          
          return false;
        }
        if (!getUser().isInitialized()) {
          
          return false;
        }
        if (!getJunket().isInitialized()) {
          
          return false;
        }
        return true;
      }
      
      @Override
	public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              freeTimes_ = input.readInt32();
              break;
            }
            case 26: {
              cn.mxz.protocols.user.UserBaseP.UserBasePro.Builder subBuilder = cn.mxz.protocols.user.UserBaseP.UserBasePro.newBuilder();
              if (hasUser()) {
                subBuilder.mergeFrom(getUser());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setUser(subBuilder.buildPartial());
              break;
            }
            case 34: {
              cn.mxz.protocols.user.fish.FishUserP.JunketPro.Builder subBuilder = cn.mxz.protocols.user.fish.FishUserP.JunketPro.newBuilder();
              if (hasJunket()) {
                subBuilder.mergeFrom(getJunket());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setJunket(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 freeTimes = 1;
      private int freeTimes_ ;
      @Override
	public boolean hasFreeTimes() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      @Override
	public int getFreeTimes() {
        return freeTimes_;
      }
      public Builder setFreeTimes(int value) {
        bitField0_ |= 0x00000001;
        freeTimes_ = value;
        onChanged();
        return this;
      }
      public Builder clearFreeTimes() {
        bitField0_ = (bitField0_ & ~0x00000001);
        freeTimes_ = 0;
        onChanged();
        return this;
      }
      
      // required .cn.mxz.protocols.user.UserBasePro user = 3;
      private cn.mxz.protocols.user.UserBaseP.UserBasePro user_ = cn.mxz.protocols.user.UserBaseP.UserBasePro.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          cn.mxz.protocols.user.UserBaseP.UserBasePro, cn.mxz.protocols.user.UserBaseP.UserBasePro.Builder, cn.mxz.protocols.user.UserBaseP.UserBaseProOrBuilder> userBuilder_;
      @Override
	public boolean hasUser() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      @Override
	public cn.mxz.protocols.user.UserBaseP.UserBasePro getUser() {
        if (userBuilder_ == null) {
          return user_;
        } else {
          return userBuilder_.getMessage();
        }
      }
      public Builder setUser(cn.mxz.protocols.user.UserBaseP.UserBasePro value) {
        if (userBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          user_ = value;
          onChanged();
        } else {
          userBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setUser(
          cn.mxz.protocols.user.UserBaseP.UserBasePro.Builder builderForValue) {
        if (userBuilder_ == null) {
          user_ = builderForValue.build();
          onChanged();
        } else {
          userBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergeUser(cn.mxz.protocols.user.UserBaseP.UserBasePro value) {
        if (userBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              user_ != cn.mxz.protocols.user.UserBaseP.UserBasePro.getDefaultInstance()) {
            user_ =
              cn.mxz.protocols.user.UserBaseP.UserBasePro.newBuilder(user_).mergeFrom(value).buildPartial();
          } else {
            user_ = value;
          }
          onChanged();
        } else {
          userBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearUser() {
        if (userBuilder_ == null) {
          user_ = cn.mxz.protocols.user.UserBaseP.UserBasePro.getDefaultInstance();
          onChanged();
        } else {
          userBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public cn.mxz.protocols.user.UserBaseP.UserBasePro.Builder getUserBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getUserFieldBuilder().getBuilder();
      }
      @Override
	public cn.mxz.protocols.user.UserBaseP.UserBaseProOrBuilder getUserOrBuilder() {
        if (userBuilder_ != null) {
          return userBuilder_.getMessageOrBuilder();
        } else {
          return user_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          cn.mxz.protocols.user.UserBaseP.UserBasePro, cn.mxz.protocols.user.UserBaseP.UserBasePro.Builder, cn.mxz.protocols.user.UserBaseP.UserBaseProOrBuilder> 
          getUserFieldBuilder() {
        if (userBuilder_ == null) {
          userBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              cn.mxz.protocols.user.UserBaseP.UserBasePro, cn.mxz.protocols.user.UserBaseP.UserBasePro.Builder, cn.mxz.protocols.user.UserBaseP.UserBaseProOrBuilder>(
                  user_,
                  getParentForChildren(),
                  isClean());
          user_ = null;
        }
        return userBuilder_;
      }
      
      // required .cn.mxz.protocols.user.fish.JunketPro junket = 4;
      private cn.mxz.protocols.user.fish.FishUserP.JunketPro junket_ = cn.mxz.protocols.user.fish.FishUserP.JunketPro.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          cn.mxz.protocols.user.fish.FishUserP.JunketPro, cn.mxz.protocols.user.fish.FishUserP.JunketPro.Builder, cn.mxz.protocols.user.fish.FishUserP.JunketProOrBuilder> junketBuilder_;
      @Override
	public boolean hasJunket() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      @Override
	public cn.mxz.protocols.user.fish.FishUserP.JunketPro getJunket() {
        if (junketBuilder_ == null) {
          return junket_;
        } else {
          return junketBuilder_.getMessage();
        }
      }
      public Builder setJunket(cn.mxz.protocols.user.fish.FishUserP.JunketPro value) {
        if (junketBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          junket_ = value;
          onChanged();
        } else {
          junketBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder setJunket(
          cn.mxz.protocols.user.fish.FishUserP.JunketPro.Builder builderForValue) {
        if (junketBuilder_ == null) {
          junket_ = builderForValue.build();
          onChanged();
        } else {
          junketBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder mergeJunket(cn.mxz.protocols.user.fish.FishUserP.JunketPro value) {
        if (junketBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              junket_ != cn.mxz.protocols.user.fish.FishUserP.JunketPro.getDefaultInstance()) {
            junket_ =
              cn.mxz.protocols.user.fish.FishUserP.JunketPro.newBuilder(junket_).mergeFrom(value).buildPartial();
          } else {
            junket_ = value;
          }
          onChanged();
        } else {
          junketBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder clearJunket() {
        if (junketBuilder_ == null) {
          junket_ = cn.mxz.protocols.user.fish.FishUserP.JunketPro.getDefaultInstance();
          onChanged();
        } else {
          junketBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      public cn.mxz.protocols.user.fish.FishUserP.JunketPro.Builder getJunketBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getJunketFieldBuilder().getBuilder();
      }
      @Override
	public cn.mxz.protocols.user.fish.FishUserP.JunketProOrBuilder getJunketOrBuilder() {
        if (junketBuilder_ != null) {
          return junketBuilder_.getMessageOrBuilder();
        } else {
          return junket_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          cn.mxz.protocols.user.fish.FishUserP.JunketPro, cn.mxz.protocols.user.fish.FishUserP.JunketPro.Builder, cn.mxz.protocols.user.fish.FishUserP.JunketProOrBuilder> 
          getJunketFieldBuilder() {
        if (junketBuilder_ == null) {
          junketBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              cn.mxz.protocols.user.fish.FishUserP.JunketPro, cn.mxz.protocols.user.fish.FishUserP.JunketPro.Builder, cn.mxz.protocols.user.fish.FishUserP.JunketProOrBuilder>(
                  junket_,
                  getParentForChildren(),
                  isClean());
          junket_ = null;
        }
        return junketBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:cn.mxz.protocols.user.fish.FishUserPro)
    }
    
    static {
      defaultInstance = new FishUserPro(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:cn.mxz.protocols.user.fish.FishUserPro)
  }
  
  public interface JunketProOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 now = 1;
    boolean hasNow();
    int getNow();
    
    // required int32 max = 2;
    boolean hasMax();
    int getMax();
    
    // repeated .cn.mxz.protocols.user.fish.FishPro fishs = 3;
    java.util.List<cn.mxz.protocols.user.fish.FishUserP.FishPro> 
        getFishsList();
    cn.mxz.protocols.user.fish.FishUserP.FishPro getFishs(int index);
    int getFishsCount();
    java.util.List<? extends cn.mxz.protocols.user.fish.FishUserP.FishProOrBuilder> 
        getFishsOrBuilderList();
    cn.mxz.protocols.user.fish.FishUserP.FishProOrBuilder getFishsOrBuilder(
        int index);
  }
  public static final class JunketPro extends
      com.google.protobuf.GeneratedMessage
      implements JunketProOrBuilder {
    // Use JunketPro.newBuilder() to construct.
    private JunketPro(Builder builder) {
      super(builder);
    }
    private JunketPro(boolean noInit) {}
    
    private static final JunketPro defaultInstance;
    public static JunketPro getDefaultInstance() {
      return defaultInstance;
    }
    
    @Override
	public JunketPro getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.mxz.protocols.user.fish.FishUserP.internal_static_cn_mxz_protocols_user_fish_JunketPro_descriptor;
    }
    
    @Override
	protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.mxz.protocols.user.fish.FishUserP.internal_static_cn_mxz_protocols_user_fish_JunketPro_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 now = 1;
    public static final int NOW_FIELD_NUMBER = 1;
    private int now_;
    @Override
	public boolean hasNow() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    @Override
	public int getNow() {
      return now_;
    }
    
    // required int32 max = 2;
    public static final int MAX_FIELD_NUMBER = 2;
    private int max_;
    @Override
	public boolean hasMax() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    @Override
	public int getMax() {
      return max_;
    }
    
    // repeated .cn.mxz.protocols.user.fish.FishPro fishs = 3;
    public static final int FISHS_FIELD_NUMBER = 3;
    private java.util.List<cn.mxz.protocols.user.fish.FishUserP.FishPro> fishs_;
    @Override
	public java.util.List<cn.mxz.protocols.user.fish.FishUserP.FishPro> getFishsList() {
      return fishs_;
    }
    @Override
	public java.util.List<? extends cn.mxz.protocols.user.fish.FishUserP.FishProOrBuilder> 
        getFishsOrBuilderList() {
      return fishs_;
    }
    @Override
	public int getFishsCount() {
      return fishs_.size();
    }
    @Override
	public cn.mxz.protocols.user.fish.FishUserP.FishPro getFishs(int index) {
      return fishs_.get(index);
    }
    @Override
	public cn.mxz.protocols.user.fish.FishUserP.FishProOrBuilder getFishsOrBuilder(
        int index) {
      return fishs_.get(index);
    }
    
    private void initFields() {
      now_ = 0;
      max_ = 0;
      fishs_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    @Override
	public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasNow()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMax()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getFishsCount(); i++) {
        if (!getFishs(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    @Override
	public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, now_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, max_);
      }
      for (int i = 0; i < fishs_.size(); i++) {
        output.writeMessage(3, fishs_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    @Override
	public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, now_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, max_);
      }
      for (int i = 0; i < fishs_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, fishs_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static cn.mxz.protocols.user.fish.FishUserP.JunketPro parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static cn.mxz.protocols.user.fish.FishUserP.JunketPro parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static cn.mxz.protocols.user.fish.FishUserP.JunketPro parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static cn.mxz.protocols.user.fish.FishUserP.JunketPro parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static cn.mxz.protocols.user.fish.FishUserP.JunketPro parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static cn.mxz.protocols.user.fish.FishUserP.JunketPro parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static cn.mxz.protocols.user.fish.FishUserP.JunketPro parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static cn.mxz.protocols.user.fish.FishUserP.JunketPro parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static cn.mxz.protocols.user.fish.FishUserP.JunketPro parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static cn.mxz.protocols.user.fish.FishUserP.JunketPro parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    @Override
	public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cn.mxz.protocols.user.fish.FishUserP.JunketPro prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    @Override
	public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements cn.mxz.protocols.user.fish.FishUserP.JunketProOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.mxz.protocols.user.fish.FishUserP.internal_static_cn_mxz_protocols_user_fish_JunketPro_descriptor;
      }
      
      @Override
	protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.mxz.protocols.user.fish.FishUserP.internal_static_cn_mxz_protocols_user_fish_JunketPro_fieldAccessorTable;
      }
      
      // Construct using cn.mxz.protocols.user.fish.FishUserP.JunketPro.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getFishsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      @Override
	public Builder clear() {
        super.clear();
        now_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        max_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (fishsBuilder_ == null) {
          fishs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          fishsBuilder_.clear();
        }
        return this;
      }
      
      @Override
	public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      @Override
	public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.mxz.protocols.user.fish.FishUserP.JunketPro.getDescriptor();
      }
      
      @Override
	public cn.mxz.protocols.user.fish.FishUserP.JunketPro getDefaultInstanceForType() {
        return cn.mxz.protocols.user.fish.FishUserP.JunketPro.getDefaultInstance();
      }
      
      @Override
	public cn.mxz.protocols.user.fish.FishUserP.JunketPro build() {
        cn.mxz.protocols.user.fish.FishUserP.JunketPro result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private cn.mxz.protocols.user.fish.FishUserP.JunketPro buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        cn.mxz.protocols.user.fish.FishUserP.JunketPro result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      @Override
	public cn.mxz.protocols.user.fish.FishUserP.JunketPro buildPartial() {
        cn.mxz.protocols.user.fish.FishUserP.JunketPro result = new cn.mxz.protocols.user.fish.FishUserP.JunketPro(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.now_ = now_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.max_ = max_;
        if (fishsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            fishs_ = java.util.Collections.unmodifiableList(fishs_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.fishs_ = fishs_;
        } else {
          result.fishs_ = fishsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      @Override
	public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.mxz.protocols.user.fish.FishUserP.JunketPro) {
          return mergeFrom((cn.mxz.protocols.user.fish.FishUserP.JunketPro)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(cn.mxz.protocols.user.fish.FishUserP.JunketPro other) {
        if (other == cn.mxz.protocols.user.fish.FishUserP.JunketPro.getDefaultInstance()) return this;
        if (other.hasNow()) {
          setNow(other.getNow());
        }
        if (other.hasMax()) {
          setMax(other.getMax());
        }
        if (fishsBuilder_ == null) {
          if (!other.fishs_.isEmpty()) {
            if (fishs_.isEmpty()) {
              fishs_ = other.fishs_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureFishsIsMutable();
              fishs_.addAll(other.fishs_);
            }
            onChanged();
          }
        } else {
          if (!other.fishs_.isEmpty()) {
            if (fishsBuilder_.isEmpty()) {
              fishsBuilder_.dispose();
              fishsBuilder_ = null;
              fishs_ = other.fishs_;
              bitField0_ = (bitField0_ & ~0x00000004);
              fishsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getFishsFieldBuilder() : null;
            } else {
              fishsBuilder_.addAllMessages(other.fishs_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      @Override
	public final boolean isInitialized() {
        if (!hasNow()) {
          
          return false;
        }
        if (!hasMax()) {
          
          return false;
        }
        for (int i = 0; i < getFishsCount(); i++) {
          if (!getFishs(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      @Override
	public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              now_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              max_ = input.readInt32();
              break;
            }
            case 26: {
              cn.mxz.protocols.user.fish.FishUserP.FishPro.Builder subBuilder = cn.mxz.protocols.user.fish.FishUserP.FishPro.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addFishs(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 now = 1;
      private int now_ ;
      @Override
	public boolean hasNow() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      @Override
	public int getNow() {
        return now_;
      }
      public Builder setNow(int value) {
        bitField0_ |= 0x00000001;
        now_ = value;
        onChanged();
        return this;
      }
      public Builder clearNow() {
        bitField0_ = (bitField0_ & ~0x00000001);
        now_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 max = 2;
      private int max_ ;
      @Override
	public boolean hasMax() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      @Override
	public int getMax() {
        return max_;
      }
      public Builder setMax(int value) {
        bitField0_ |= 0x00000002;
        max_ = value;
        onChanged();
        return this;
      }
      public Builder clearMax() {
        bitField0_ = (bitField0_ & ~0x00000002);
        max_ = 0;
        onChanged();
        return this;
      }
      
      // repeated .cn.mxz.protocols.user.fish.FishPro fishs = 3;
      private java.util.List<cn.mxz.protocols.user.fish.FishUserP.FishPro> fishs_ =
        java.util.Collections.emptyList();
      private void ensureFishsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          fishs_ = new java.util.ArrayList<cn.mxz.protocols.user.fish.FishUserP.FishPro>(fishs_);
          bitField0_ |= 0x00000004;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          cn.mxz.protocols.user.fish.FishUserP.FishPro, cn.mxz.protocols.user.fish.FishUserP.FishPro.Builder, cn.mxz.protocols.user.fish.FishUserP.FishProOrBuilder> fishsBuilder_;
      
      @Override
	public java.util.List<cn.mxz.protocols.user.fish.FishUserP.FishPro> getFishsList() {
        if (fishsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(fishs_);
        } else {
          return fishsBuilder_.getMessageList();
        }
      }
      @Override
	public int getFishsCount() {
        if (fishsBuilder_ == null) {
          return fishs_.size();
        } else {
          return fishsBuilder_.getCount();
        }
      }
      @Override
	public cn.mxz.protocols.user.fish.FishUserP.FishPro getFishs(int index) {
        if (fishsBuilder_ == null) {
          return fishs_.get(index);
        } else {
          return fishsBuilder_.getMessage(index);
        }
      }
      public Builder setFishs(
          int index, cn.mxz.protocols.user.fish.FishUserP.FishPro value) {
        if (fishsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFishsIsMutable();
          fishs_.set(index, value);
          onChanged();
        } else {
          fishsBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setFishs(
          int index, cn.mxz.protocols.user.fish.FishUserP.FishPro.Builder builderForValue) {
        if (fishsBuilder_ == null) {
          ensureFishsIsMutable();
          fishs_.set(index, builderForValue.build());
          onChanged();
        } else {
          fishsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addFishs(cn.mxz.protocols.user.fish.FishUserP.FishPro value) {
        if (fishsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFishsIsMutable();
          fishs_.add(value);
          onChanged();
        } else {
          fishsBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addFishs(
          int index, cn.mxz.protocols.user.fish.FishUserP.FishPro value) {
        if (fishsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFishsIsMutable();
          fishs_.add(index, value);
          onChanged();
        } else {
          fishsBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addFishs(
          cn.mxz.protocols.user.fish.FishUserP.FishPro.Builder builderForValue) {
        if (fishsBuilder_ == null) {
          ensureFishsIsMutable();
          fishs_.add(builderForValue.build());
          onChanged();
        } else {
          fishsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addFishs(
          int index, cn.mxz.protocols.user.fish.FishUserP.FishPro.Builder builderForValue) {
        if (fishsBuilder_ == null) {
          ensureFishsIsMutable();
          fishs_.add(index, builderForValue.build());
          onChanged();
        } else {
          fishsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllFishs(
          java.lang.Iterable<? extends cn.mxz.protocols.user.fish.FishUserP.FishPro> values) {
        if (fishsBuilder_ == null) {
          ensureFishsIsMutable();
          super.addAll(values, fishs_);
          onChanged();
        } else {
          fishsBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearFishs() {
        if (fishsBuilder_ == null) {
          fishs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          fishsBuilder_.clear();
        }
        return this;
      }
      public Builder removeFishs(int index) {
        if (fishsBuilder_ == null) {
          ensureFishsIsMutable();
          fishs_.remove(index);
          onChanged();
        } else {
          fishsBuilder_.remove(index);
        }
        return this;
      }
      public cn.mxz.protocols.user.fish.FishUserP.FishPro.Builder getFishsBuilder(
          int index) {
        return getFishsFieldBuilder().getBuilder(index);
      }
      @Override
	public cn.mxz.protocols.user.fish.FishUserP.FishProOrBuilder getFishsOrBuilder(
          int index) {
        if (fishsBuilder_ == null) {
          return fishs_.get(index);  } else {
          return fishsBuilder_.getMessageOrBuilder(index);
        }
      }
      @Override
	public java.util.List<? extends cn.mxz.protocols.user.fish.FishUserP.FishProOrBuilder> 
           getFishsOrBuilderList() {
        if (fishsBuilder_ != null) {
          return fishsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(fishs_);
        }
      }
      public cn.mxz.protocols.user.fish.FishUserP.FishPro.Builder addFishsBuilder() {
        return getFishsFieldBuilder().addBuilder(
            cn.mxz.protocols.user.fish.FishUserP.FishPro.getDefaultInstance());
      }
      public cn.mxz.protocols.user.fish.FishUserP.FishPro.Builder addFishsBuilder(
          int index) {
        return getFishsFieldBuilder().addBuilder(
            index, cn.mxz.protocols.user.fish.FishUserP.FishPro.getDefaultInstance());
      }
      public java.util.List<cn.mxz.protocols.user.fish.FishUserP.FishPro.Builder> 
           getFishsBuilderList() {
        return getFishsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          cn.mxz.protocols.user.fish.FishUserP.FishPro, cn.mxz.protocols.user.fish.FishUserP.FishPro.Builder, cn.mxz.protocols.user.fish.FishUserP.FishProOrBuilder> 
          getFishsFieldBuilder() {
        if (fishsBuilder_ == null) {
          fishsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              cn.mxz.protocols.user.fish.FishUserP.FishPro, cn.mxz.protocols.user.fish.FishUserP.FishPro.Builder, cn.mxz.protocols.user.fish.FishUserP.FishProOrBuilder>(
                  fishs_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          fishs_ = null;
        }
        return fishsBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:cn.mxz.protocols.user.fish.JunketPro)
    }
    
    static {
      defaultInstance = new JunketPro(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:cn.mxz.protocols.user.fish.JunketPro)
  }
  
  public interface FishProOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 id = 1;
    boolean hasId();
    int getId();
    
    // required int32 type = 3;
    boolean hasType();
    int getType();
    
    // required int32 count = 4;
    boolean hasCount();
    int getCount();
  }
  public static final class FishPro extends
      com.google.protobuf.GeneratedMessage
      implements FishProOrBuilder {
    // Use FishPro.newBuilder() to construct.
    private FishPro(Builder builder) {
      super(builder);
    }
    private FishPro(boolean noInit) {}
    
    private static final FishPro defaultInstance;
    public static FishPro getDefaultInstance() {
      return defaultInstance;
    }
    
    @Override
	public FishPro getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.mxz.protocols.user.fish.FishUserP.internal_static_cn_mxz_protocols_user_fish_FishPro_descriptor;
    }
    
    @Override
	protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.mxz.protocols.user.fish.FishUserP.internal_static_cn_mxz_protocols_user_fish_FishPro_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    @Override
	public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    @Override
	public int getId() {
      return id_;
    }
    
    // required int32 type = 3;
    public static final int TYPE_FIELD_NUMBER = 3;
    private int type_;
    @Override
	public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    @Override
	public int getType() {
      return type_;
    }
    
    // required int32 count = 4;
    public static final int COUNT_FIELD_NUMBER = 4;
    private int count_;
    @Override
	public boolean hasCount() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    @Override
	public int getCount() {
      return count_;
    }
    
    private void initFields() {
      id_ = 0;
      type_ = 0;
      count_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    @Override
	public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    @Override
	public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(3, type_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(4, count_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    @Override
	public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, type_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, count_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static cn.mxz.protocols.user.fish.FishUserP.FishPro parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static cn.mxz.protocols.user.fish.FishUserP.FishPro parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static cn.mxz.protocols.user.fish.FishUserP.FishPro parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static cn.mxz.protocols.user.fish.FishUserP.FishPro parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static cn.mxz.protocols.user.fish.FishUserP.FishPro parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static cn.mxz.protocols.user.fish.FishUserP.FishPro parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static cn.mxz.protocols.user.fish.FishUserP.FishPro parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static cn.mxz.protocols.user.fish.FishUserP.FishPro parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static cn.mxz.protocols.user.fish.FishUserP.FishPro parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static cn.mxz.protocols.user.fish.FishUserP.FishPro parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    @Override
	public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cn.mxz.protocols.user.fish.FishUserP.FishPro prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    @Override
	public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements cn.mxz.protocols.user.fish.FishUserP.FishProOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.mxz.protocols.user.fish.FishUserP.internal_static_cn_mxz_protocols_user_fish_FishPro_descriptor;
      }
      
      @Override
	protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.mxz.protocols.user.fish.FishUserP.internal_static_cn_mxz_protocols_user_fish_FishPro_fieldAccessorTable;
      }
      
      // Construct using cn.mxz.protocols.user.fish.FishUserP.FishPro.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      @Override
	public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        count_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      @Override
	public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      @Override
	public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.mxz.protocols.user.fish.FishUserP.FishPro.getDescriptor();
      }
      
      @Override
	public cn.mxz.protocols.user.fish.FishUserP.FishPro getDefaultInstanceForType() {
        return cn.mxz.protocols.user.fish.FishUserP.FishPro.getDefaultInstance();
      }
      
      @Override
	public cn.mxz.protocols.user.fish.FishUserP.FishPro build() {
        cn.mxz.protocols.user.fish.FishUserP.FishPro result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private cn.mxz.protocols.user.fish.FishUserP.FishPro buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        cn.mxz.protocols.user.fish.FishUserP.FishPro result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      @Override
	public cn.mxz.protocols.user.fish.FishUserP.FishPro buildPartial() {
        cn.mxz.protocols.user.fish.FishUserP.FishPro result = new cn.mxz.protocols.user.fish.FishUserP.FishPro(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.count_ = count_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      @Override
	public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.mxz.protocols.user.fish.FishUserP.FishPro) {
          return mergeFrom((cn.mxz.protocols.user.fish.FishUserP.FishPro)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(cn.mxz.protocols.user.fish.FishUserP.FishPro other) {
        if (other == cn.mxz.protocols.user.fish.FishUserP.FishPro.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasCount()) {
          setCount(other.getCount());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      @Override
	public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        if (!hasCount()) {
          
          return false;
        }
        return true;
      }
      
      @Override
	public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000002;
              type_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              count_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 id = 1;
      private int id_ ;
      @Override
	public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      @Override
	public int getId() {
        return id_;
      }
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 type = 3;
      private int type_ ;
      @Override
	public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      @Override
	public int getType() {
        return type_;
      }
      public Builder setType(int value) {
        bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 count = 4;
      private int count_ ;
      @Override
	public boolean hasCount() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      @Override
	public int getCount() {
        return count_;
      }
      public Builder setCount(int value) {
        bitField0_ |= 0x00000004;
        count_ = value;
        onChanged();
        return this;
      }
      public Builder clearCount() {
        bitField0_ = (bitField0_ & ~0x00000004);
        count_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:cn.mxz.protocols.user.fish.FishPro)
    }
    
    static {
      defaultInstance = new FishPro(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:cn.mxz.protocols.user.fish.FishPro)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_mxz_protocols_user_fish_FishUserPro_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cn_mxz_protocols_user_fish_FishUserPro_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_mxz_protocols_user_fish_JunketPro_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cn_mxz_protocols_user_fish_JunketPro_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_mxz_protocols_user_fish_FishPro_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cn_mxz_protocols_user_fish_FishPro_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013fish_user.p\022\032cn.mxz.protocols.user.fis" +
      "h\032\013user_base.p\"\211\001\n\013FishUserPro\022\021\n\tfreeTi" +
      "mes\030\001 \002(\005\0220\n\004user\030\003 \002(\0132\".cn.mxz.protoco" +
      "ls.user.UserBasePro\0225\n\006junket\030\004 \002(\0132%.cn" +
      ".mxz.protocols.user.fish.JunketPro\"Y\n\tJu" +
      "nketPro\022\013\n\003now\030\001 \002(\005\022\013\n\003max\030\002 \002(\005\0222\n\005fis" +
      "hs\030\003 \003(\0132#.cn.mxz.protocols.user.fish.Fi" +
      "shPro\"2\n\007FishPro\022\n\n\002id\030\001 \002(\005\022\014\n\004type\030\003 \002" +
      "(\005\022\r\n\005count\030\004 \002(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        @Override
		public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_cn_mxz_protocols_user_fish_FishUserPro_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_cn_mxz_protocols_user_fish_FishUserPro_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_cn_mxz_protocols_user_fish_FishUserPro_descriptor,
              new java.lang.String[] { "FreeTimes", "User", "Junket", },
              cn.mxz.protocols.user.fish.FishUserP.FishUserPro.class,
              cn.mxz.protocols.user.fish.FishUserP.FishUserPro.Builder.class);
          internal_static_cn_mxz_protocols_user_fish_JunketPro_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_cn_mxz_protocols_user_fish_JunketPro_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_cn_mxz_protocols_user_fish_JunketPro_descriptor,
              new java.lang.String[] { "Now", "Max", "Fishs", },
              cn.mxz.protocols.user.fish.FishUserP.JunketPro.class,
              cn.mxz.protocols.user.fish.FishUserP.JunketPro.Builder.class);
          internal_static_cn_mxz_protocols_user_fish_FishPro_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_cn_mxz_protocols_user_fish_FishPro_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_cn_mxz_protocols_user_fish_FishPro_descriptor,
              new java.lang.String[] { "Id", "Type", "Count", },
              cn.mxz.protocols.user.fish.FishUserP.FishPro.class,
              cn.mxz.protocols.user.fish.FishUserP.FishPro.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cn.mxz.protocols.user.UserBaseP.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
