// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tower.p

package cn.mxz.protocols.user.tower;

public final class TowerP {
  private TowerP() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TowerProOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional .cn.mxz.protocols.user.tower.TowerBugPro bug = 40;
    boolean hasBug();
    cn.mxz.protocols.user.tower.TowerP.TowerBugPro getBug();
    cn.mxz.protocols.user.tower.TowerP.TowerBugProOrBuilder getBugOrBuilder();
  }
  public static final class TowerPro extends
      com.google.protobuf.GeneratedMessage
      implements TowerProOrBuilder {
    // Use TowerPro.newBuilder() to construct.
    private TowerPro(Builder builder) {
      super(builder);
    }
    private TowerPro(boolean noInit) {}
    
    private static final TowerPro defaultInstance;
    public static TowerPro getDefaultInstance() {
      return defaultInstance;
    }
    
    @Override
	public TowerPro getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.mxz.protocols.user.tower.TowerP.internal_static_cn_mxz_protocols_user_tower_TowerPro_descriptor;
    }
    
    @Override
	protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.mxz.protocols.user.tower.TowerP.internal_static_cn_mxz_protocols_user_tower_TowerPro_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional .cn.mxz.protocols.user.tower.TowerBugPro bug = 40;
    public static final int BUG_FIELD_NUMBER = 40;
    private cn.mxz.protocols.user.tower.TowerP.TowerBugPro bug_;
    @Override
	public boolean hasBug() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    @Override
	public cn.mxz.protocols.user.tower.TowerP.TowerBugPro getBug() {
      return bug_;
    }
    @Override
	public cn.mxz.protocols.user.tower.TowerP.TowerBugProOrBuilder getBugOrBuilder() {
      return bug_;
    }
    
    private void initFields() {
      bug_ = cn.mxz.protocols.user.tower.TowerP.TowerBugPro.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    @Override
	public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (hasBug()) {
        if (!getBug().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    @Override
	public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(40, bug_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    @Override
	public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(40, bug_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static cn.mxz.protocols.user.tower.TowerP.TowerPro parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static cn.mxz.protocols.user.tower.TowerP.TowerPro parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static cn.mxz.protocols.user.tower.TowerP.TowerPro parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static cn.mxz.protocols.user.tower.TowerP.TowerPro parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static cn.mxz.protocols.user.tower.TowerP.TowerPro parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static cn.mxz.protocols.user.tower.TowerP.TowerPro parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static cn.mxz.protocols.user.tower.TowerP.TowerPro parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static cn.mxz.protocols.user.tower.TowerP.TowerPro parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static cn.mxz.protocols.user.tower.TowerP.TowerPro parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static cn.mxz.protocols.user.tower.TowerP.TowerPro parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    @Override
	public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cn.mxz.protocols.user.tower.TowerP.TowerPro prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    @Override
	public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements cn.mxz.protocols.user.tower.TowerP.TowerProOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.mxz.protocols.user.tower.TowerP.internal_static_cn_mxz_protocols_user_tower_TowerPro_descriptor;
      }
      
      @Override
	protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.mxz.protocols.user.tower.TowerP.internal_static_cn_mxz_protocols_user_tower_TowerPro_fieldAccessorTable;
      }
      
      // Construct using cn.mxz.protocols.user.tower.TowerP.TowerPro.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getBugFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      @Override
	public Builder clear() {
        super.clear();
        if (bugBuilder_ == null) {
          bug_ = cn.mxz.protocols.user.tower.TowerP.TowerBugPro.getDefaultInstance();
        } else {
          bugBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      @Override
	public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      @Override
	public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.mxz.protocols.user.tower.TowerP.TowerPro.getDescriptor();
      }
      
      @Override
	public cn.mxz.protocols.user.tower.TowerP.TowerPro getDefaultInstanceForType() {
        return cn.mxz.protocols.user.tower.TowerP.TowerPro.getDefaultInstance();
      }
      
      @Override
	public cn.mxz.protocols.user.tower.TowerP.TowerPro build() {
        cn.mxz.protocols.user.tower.TowerP.TowerPro result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private cn.mxz.protocols.user.tower.TowerP.TowerPro buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        cn.mxz.protocols.user.tower.TowerP.TowerPro result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      @Override
	public cn.mxz.protocols.user.tower.TowerP.TowerPro buildPartial() {
        cn.mxz.protocols.user.tower.TowerP.TowerPro result = new cn.mxz.protocols.user.tower.TowerP.TowerPro(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (bugBuilder_ == null) {
          result.bug_ = bug_;
        } else {
          result.bug_ = bugBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      @Override
	public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.mxz.protocols.user.tower.TowerP.TowerPro) {
          return mergeFrom((cn.mxz.protocols.user.tower.TowerP.TowerPro)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(cn.mxz.protocols.user.tower.TowerP.TowerPro other) {
        if (other == cn.mxz.protocols.user.tower.TowerP.TowerPro.getDefaultInstance()) return this;
        if (other.hasBug()) {
          mergeBug(other.getBug());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      @Override
	public final boolean isInitialized() {
        if (hasBug()) {
          if (!getBug().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      @Override
	public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 322: {
              cn.mxz.protocols.user.tower.TowerP.TowerBugPro.Builder subBuilder = cn.mxz.protocols.user.tower.TowerP.TowerBugPro.newBuilder();
              if (hasBug()) {
                subBuilder.mergeFrom(getBug());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setBug(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional .cn.mxz.protocols.user.tower.TowerBugPro bug = 40;
      private cn.mxz.protocols.user.tower.TowerP.TowerBugPro bug_ = cn.mxz.protocols.user.tower.TowerP.TowerBugPro.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          cn.mxz.protocols.user.tower.TowerP.TowerBugPro, cn.mxz.protocols.user.tower.TowerP.TowerBugPro.Builder, cn.mxz.protocols.user.tower.TowerP.TowerBugProOrBuilder> bugBuilder_;
      @Override
	public boolean hasBug() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      @Override
	public cn.mxz.protocols.user.tower.TowerP.TowerBugPro getBug() {
        if (bugBuilder_ == null) {
          return bug_;
        } else {
          return bugBuilder_.getMessage();
        }
      }
      public Builder setBug(cn.mxz.protocols.user.tower.TowerP.TowerBugPro value) {
        if (bugBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          bug_ = value;
          onChanged();
        } else {
          bugBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setBug(
          cn.mxz.protocols.user.tower.TowerP.TowerBugPro.Builder builderForValue) {
        if (bugBuilder_ == null) {
          bug_ = builderForValue.build();
          onChanged();
        } else {
          bugBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeBug(cn.mxz.protocols.user.tower.TowerP.TowerBugPro value) {
        if (bugBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              bug_ != cn.mxz.protocols.user.tower.TowerP.TowerBugPro.getDefaultInstance()) {
            bug_ =
              cn.mxz.protocols.user.tower.TowerP.TowerBugPro.newBuilder(bug_).mergeFrom(value).buildPartial();
          } else {
            bug_ = value;
          }
          onChanged();
        } else {
          bugBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearBug() {
        if (bugBuilder_ == null) {
          bug_ = cn.mxz.protocols.user.tower.TowerP.TowerBugPro.getDefaultInstance();
          onChanged();
        } else {
          bugBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public cn.mxz.protocols.user.tower.TowerP.TowerBugPro.Builder getBugBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getBugFieldBuilder().getBuilder();
      }
      @Override
	public cn.mxz.protocols.user.tower.TowerP.TowerBugProOrBuilder getBugOrBuilder() {
        if (bugBuilder_ != null) {
          return bugBuilder_.getMessageOrBuilder();
        } else {
          return bug_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          cn.mxz.protocols.user.tower.TowerP.TowerBugPro, cn.mxz.protocols.user.tower.TowerP.TowerBugPro.Builder, cn.mxz.protocols.user.tower.TowerP.TowerBugProOrBuilder> 
          getBugFieldBuilder() {
        if (bugBuilder_ == null) {
          bugBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              cn.mxz.protocols.user.tower.TowerP.TowerBugPro, cn.mxz.protocols.user.tower.TowerP.TowerBugPro.Builder, cn.mxz.protocols.user.tower.TowerP.TowerBugProOrBuilder>(
                  bug_,
                  getParentForChildren(),
                  isClean());
          bug_ = null;
        }
        return bugBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:cn.mxz.protocols.user.tower.TowerPro)
    }
    
    static {
      defaultInstance = new TowerPro(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:cn.mxz.protocols.user.tower.TowerPro)
  }
  
  public interface TowerBugProOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 remainSec = 40;
    boolean hasRemainSec();
    int getRemainSec();
    
    // required bool isMine = 50;
    boolean hasIsMine();
    boolean getIsMine();
    
    // required .cn.mxz.protocols.user.UserBasePro finder = 60;
    boolean hasFinder();
    cn.mxz.protocols.user.UserBaseP.UserBasePro getFinder();
    cn.mxz.protocols.user.UserBaseP.UserBaseProOrBuilder getFinderOrBuilder();
  }
  public static final class TowerBugPro extends
      com.google.protobuf.GeneratedMessage
      implements TowerBugProOrBuilder {
    // Use TowerBugPro.newBuilder() to construct.
    private TowerBugPro(Builder builder) {
      super(builder);
    }
    private TowerBugPro(boolean noInit) {}
    
    private static final TowerBugPro defaultInstance;
    public static TowerBugPro getDefaultInstance() {
      return defaultInstance;
    }
    
    @Override
	public TowerBugPro getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.mxz.protocols.user.tower.TowerP.internal_static_cn_mxz_protocols_user_tower_TowerBugPro_descriptor;
    }
    
    @Override
	protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.mxz.protocols.user.tower.TowerP.internal_static_cn_mxz_protocols_user_tower_TowerBugPro_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 remainSec = 40;
    public static final int REMAINSEC_FIELD_NUMBER = 40;
    private int remainSec_;
    @Override
	public boolean hasRemainSec() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    @Override
	public int getRemainSec() {
      return remainSec_;
    }
    
    // required bool isMine = 50;
    public static final int ISMINE_FIELD_NUMBER = 50;
    private boolean isMine_;
    @Override
	public boolean hasIsMine() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    @Override
	public boolean getIsMine() {
      return isMine_;
    }
    
    // required .cn.mxz.protocols.user.UserBasePro finder = 60;
    public static final int FINDER_FIELD_NUMBER = 60;
    private cn.mxz.protocols.user.UserBaseP.UserBasePro finder_;
    @Override
	public boolean hasFinder() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    @Override
	public cn.mxz.protocols.user.UserBaseP.UserBasePro getFinder() {
      return finder_;
    }
    @Override
	public cn.mxz.protocols.user.UserBaseP.UserBaseProOrBuilder getFinderOrBuilder() {
      return finder_;
    }
    
    private void initFields() {
      remainSec_ = 0;
      isMine_ = false;
      finder_ = cn.mxz.protocols.user.UserBaseP.UserBasePro.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    @Override
	public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasRemainSec()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIsMine()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFinder()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getFinder().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    @Override
	public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(40, remainSec_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(50, isMine_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(60, finder_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    @Override
	public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(40, remainSec_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(50, isMine_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(60, finder_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static cn.mxz.protocols.user.tower.TowerP.TowerBugPro parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static cn.mxz.protocols.user.tower.TowerP.TowerBugPro parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static cn.mxz.protocols.user.tower.TowerP.TowerBugPro parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static cn.mxz.protocols.user.tower.TowerP.TowerBugPro parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static cn.mxz.protocols.user.tower.TowerP.TowerBugPro parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static cn.mxz.protocols.user.tower.TowerP.TowerBugPro parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static cn.mxz.protocols.user.tower.TowerP.TowerBugPro parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static cn.mxz.protocols.user.tower.TowerP.TowerBugPro parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static cn.mxz.protocols.user.tower.TowerP.TowerBugPro parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static cn.mxz.protocols.user.tower.TowerP.TowerBugPro parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    @Override
	public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cn.mxz.protocols.user.tower.TowerP.TowerBugPro prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    @Override
	public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements cn.mxz.protocols.user.tower.TowerP.TowerBugProOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.mxz.protocols.user.tower.TowerP.internal_static_cn_mxz_protocols_user_tower_TowerBugPro_descriptor;
      }
      
      @Override
	protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.mxz.protocols.user.tower.TowerP.internal_static_cn_mxz_protocols_user_tower_TowerBugPro_fieldAccessorTable;
      }
      
      // Construct using cn.mxz.protocols.user.tower.TowerP.TowerBugPro.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getFinderFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      @Override
	public Builder clear() {
        super.clear();
        remainSec_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        isMine_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (finderBuilder_ == null) {
          finder_ = cn.mxz.protocols.user.UserBaseP.UserBasePro.getDefaultInstance();
        } else {
          finderBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      @Override
	public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      @Override
	public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.mxz.protocols.user.tower.TowerP.TowerBugPro.getDescriptor();
      }
      
      @Override
	public cn.mxz.protocols.user.tower.TowerP.TowerBugPro getDefaultInstanceForType() {
        return cn.mxz.protocols.user.tower.TowerP.TowerBugPro.getDefaultInstance();
      }
      
      @Override
	public cn.mxz.protocols.user.tower.TowerP.TowerBugPro build() {
        cn.mxz.protocols.user.tower.TowerP.TowerBugPro result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private cn.mxz.protocols.user.tower.TowerP.TowerBugPro buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        cn.mxz.protocols.user.tower.TowerP.TowerBugPro result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      @Override
	public cn.mxz.protocols.user.tower.TowerP.TowerBugPro buildPartial() {
        cn.mxz.protocols.user.tower.TowerP.TowerBugPro result = new cn.mxz.protocols.user.tower.TowerP.TowerBugPro(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.remainSec_ = remainSec_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.isMine_ = isMine_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (finderBuilder_ == null) {
          result.finder_ = finder_;
        } else {
          result.finder_ = finderBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      @Override
	public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.mxz.protocols.user.tower.TowerP.TowerBugPro) {
          return mergeFrom((cn.mxz.protocols.user.tower.TowerP.TowerBugPro)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(cn.mxz.protocols.user.tower.TowerP.TowerBugPro other) {
        if (other == cn.mxz.protocols.user.tower.TowerP.TowerBugPro.getDefaultInstance()) return this;
        if (other.hasRemainSec()) {
          setRemainSec(other.getRemainSec());
        }
        if (other.hasIsMine()) {
          setIsMine(other.getIsMine());
        }
        if (other.hasFinder()) {
          mergeFinder(other.getFinder());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      @Override
	public final boolean isInitialized() {
        if (!hasRemainSec()) {
          
          return false;
        }
        if (!hasIsMine()) {
          
          return false;
        }
        if (!hasFinder()) {
          
          return false;
        }
        if (!getFinder().isInitialized()) {
          
          return false;
        }
        return true;
      }
      
      @Override
	public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 320: {
              bitField0_ |= 0x00000001;
              remainSec_ = input.readInt32();
              break;
            }
            case 400: {
              bitField0_ |= 0x00000002;
              isMine_ = input.readBool();
              break;
            }
            case 482: {
              cn.mxz.protocols.user.UserBaseP.UserBasePro.Builder subBuilder = cn.mxz.protocols.user.UserBaseP.UserBasePro.newBuilder();
              if (hasFinder()) {
                subBuilder.mergeFrom(getFinder());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setFinder(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 remainSec = 40;
      private int remainSec_ ;
      @Override
	public boolean hasRemainSec() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      @Override
	public int getRemainSec() {
        return remainSec_;
      }
      public Builder setRemainSec(int value) {
        bitField0_ |= 0x00000001;
        remainSec_ = value;
        onChanged();
        return this;
      }
      public Builder clearRemainSec() {
        bitField0_ = (bitField0_ & ~0x00000001);
        remainSec_ = 0;
        onChanged();
        return this;
      }
      
      // required bool isMine = 50;
      private boolean isMine_ ;
      @Override
	public boolean hasIsMine() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      @Override
	public boolean getIsMine() {
        return isMine_;
      }
      public Builder setIsMine(boolean value) {
        bitField0_ |= 0x00000002;
        isMine_ = value;
        onChanged();
        return this;
      }
      public Builder clearIsMine() {
        bitField0_ = (bitField0_ & ~0x00000002);
        isMine_ = false;
        onChanged();
        return this;
      }
      
      // required .cn.mxz.protocols.user.UserBasePro finder = 60;
      private cn.mxz.protocols.user.UserBaseP.UserBasePro finder_ = cn.mxz.protocols.user.UserBaseP.UserBasePro.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          cn.mxz.protocols.user.UserBaseP.UserBasePro, cn.mxz.protocols.user.UserBaseP.UserBasePro.Builder, cn.mxz.protocols.user.UserBaseP.UserBaseProOrBuilder> finderBuilder_;
      @Override
	public boolean hasFinder() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      @Override
	public cn.mxz.protocols.user.UserBaseP.UserBasePro getFinder() {
        if (finderBuilder_ == null) {
          return finder_;
        } else {
          return finderBuilder_.getMessage();
        }
      }
      public Builder setFinder(cn.mxz.protocols.user.UserBaseP.UserBasePro value) {
        if (finderBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          finder_ = value;
          onChanged();
        } else {
          finderBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder setFinder(
          cn.mxz.protocols.user.UserBaseP.UserBasePro.Builder builderForValue) {
        if (finderBuilder_ == null) {
          finder_ = builderForValue.build();
          onChanged();
        } else {
          finderBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder mergeFinder(cn.mxz.protocols.user.UserBaseP.UserBasePro value) {
        if (finderBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              finder_ != cn.mxz.protocols.user.UserBaseP.UserBasePro.getDefaultInstance()) {
            finder_ =
              cn.mxz.protocols.user.UserBaseP.UserBasePro.newBuilder(finder_).mergeFrom(value).buildPartial();
          } else {
            finder_ = value;
          }
          onChanged();
        } else {
          finderBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder clearFinder() {
        if (finderBuilder_ == null) {
          finder_ = cn.mxz.protocols.user.UserBaseP.UserBasePro.getDefaultInstance();
          onChanged();
        } else {
          finderBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      public cn.mxz.protocols.user.UserBaseP.UserBasePro.Builder getFinderBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getFinderFieldBuilder().getBuilder();
      }
      @Override
	public cn.mxz.protocols.user.UserBaseP.UserBaseProOrBuilder getFinderOrBuilder() {
        if (finderBuilder_ != null) {
          return finderBuilder_.getMessageOrBuilder();
        } else {
          return finder_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          cn.mxz.protocols.user.UserBaseP.UserBasePro, cn.mxz.protocols.user.UserBaseP.UserBasePro.Builder, cn.mxz.protocols.user.UserBaseP.UserBaseProOrBuilder> 
          getFinderFieldBuilder() {
        if (finderBuilder_ == null) {
          finderBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              cn.mxz.protocols.user.UserBaseP.UserBasePro, cn.mxz.protocols.user.UserBaseP.UserBasePro.Builder, cn.mxz.protocols.user.UserBaseP.UserBaseProOrBuilder>(
                  finder_,
                  getParentForChildren(),
                  isClean());
          finder_ = null;
        }
        return finderBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:cn.mxz.protocols.user.tower.TowerBugPro)
    }
    
    static {
      defaultInstance = new TowerBugPro(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:cn.mxz.protocols.user.tower.TowerBugPro)
  }
  
  public interface FightingRewardProOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 score = 10;
    boolean hasScore();
    int getScore();
    
    // required int32 catchScore = 20;
    boolean hasCatchScore();
    int getCatchScore();
  }
  public static final class FightingRewardPro extends
      com.google.protobuf.GeneratedMessage
      implements FightingRewardProOrBuilder {
    // Use FightingRewardPro.newBuilder() to construct.
    private FightingRewardPro(Builder builder) {
      super(builder);
    }
    private FightingRewardPro(boolean noInit) {}
    
    private static final FightingRewardPro defaultInstance;
    public static FightingRewardPro getDefaultInstance() {
      return defaultInstance;
    }
    
    @Override
	public FightingRewardPro getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.mxz.protocols.user.tower.TowerP.internal_static_cn_mxz_protocols_user_tower_FightingRewardPro_descriptor;
    }
    
    @Override
	protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.mxz.protocols.user.tower.TowerP.internal_static_cn_mxz_protocols_user_tower_FightingRewardPro_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 score = 10;
    public static final int SCORE_FIELD_NUMBER = 10;
    private int score_;
    @Override
	public boolean hasScore() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    @Override
	public int getScore() {
      return score_;
    }
    
    // required int32 catchScore = 20;
    public static final int CATCHSCORE_FIELD_NUMBER = 20;
    private int catchScore_;
    @Override
	public boolean hasCatchScore() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    @Override
	public int getCatchScore() {
      return catchScore_;
    }
    
    private void initFields() {
      score_ = 0;
      catchScore_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    @Override
	public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasScore()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCatchScore()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    @Override
	public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(10, score_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(20, catchScore_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    @Override
	public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, score_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(20, catchScore_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static cn.mxz.protocols.user.tower.TowerP.FightingRewardPro parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static cn.mxz.protocols.user.tower.TowerP.FightingRewardPro parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static cn.mxz.protocols.user.tower.TowerP.FightingRewardPro parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static cn.mxz.protocols.user.tower.TowerP.FightingRewardPro parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static cn.mxz.protocols.user.tower.TowerP.FightingRewardPro parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static cn.mxz.protocols.user.tower.TowerP.FightingRewardPro parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static cn.mxz.protocols.user.tower.TowerP.FightingRewardPro parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static cn.mxz.protocols.user.tower.TowerP.FightingRewardPro parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static cn.mxz.protocols.user.tower.TowerP.FightingRewardPro parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static cn.mxz.protocols.user.tower.TowerP.FightingRewardPro parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    @Override
	public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cn.mxz.protocols.user.tower.TowerP.FightingRewardPro prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    @Override
	public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements cn.mxz.protocols.user.tower.TowerP.FightingRewardProOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.mxz.protocols.user.tower.TowerP.internal_static_cn_mxz_protocols_user_tower_FightingRewardPro_descriptor;
      }
      
      @Override
	protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.mxz.protocols.user.tower.TowerP.internal_static_cn_mxz_protocols_user_tower_FightingRewardPro_fieldAccessorTable;
      }
      
      // Construct using cn.mxz.protocols.user.tower.TowerP.FightingRewardPro.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      @Override
	public Builder clear() {
        super.clear();
        score_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        catchScore_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      @Override
	public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      @Override
	public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.mxz.protocols.user.tower.TowerP.FightingRewardPro.getDescriptor();
      }
      
      @Override
	public cn.mxz.protocols.user.tower.TowerP.FightingRewardPro getDefaultInstanceForType() {
        return cn.mxz.protocols.user.tower.TowerP.FightingRewardPro.getDefaultInstance();
      }
      
      @Override
	public cn.mxz.protocols.user.tower.TowerP.FightingRewardPro build() {
        cn.mxz.protocols.user.tower.TowerP.FightingRewardPro result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private cn.mxz.protocols.user.tower.TowerP.FightingRewardPro buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        cn.mxz.protocols.user.tower.TowerP.FightingRewardPro result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      @Override
	public cn.mxz.protocols.user.tower.TowerP.FightingRewardPro buildPartial() {
        cn.mxz.protocols.user.tower.TowerP.FightingRewardPro result = new cn.mxz.protocols.user.tower.TowerP.FightingRewardPro(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.score_ = score_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.catchScore_ = catchScore_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      @Override
	public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.mxz.protocols.user.tower.TowerP.FightingRewardPro) {
          return mergeFrom((cn.mxz.protocols.user.tower.TowerP.FightingRewardPro)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(cn.mxz.protocols.user.tower.TowerP.FightingRewardPro other) {
        if (other == cn.mxz.protocols.user.tower.TowerP.FightingRewardPro.getDefaultInstance()) return this;
        if (other.hasScore()) {
          setScore(other.getScore());
        }
        if (other.hasCatchScore()) {
          setCatchScore(other.getCatchScore());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      @Override
	public final boolean isInitialized() {
        if (!hasScore()) {
          
          return false;
        }
        if (!hasCatchScore()) {
          
          return false;
        }
        return true;
      }
      
      @Override
	public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 80: {
              bitField0_ |= 0x00000001;
              score_ = input.readInt32();
              break;
            }
            case 160: {
              bitField0_ |= 0x00000002;
              catchScore_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 score = 10;
      private int score_ ;
      @Override
	public boolean hasScore() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      @Override
	public int getScore() {
        return score_;
      }
      public Builder setScore(int value) {
        bitField0_ |= 0x00000001;
        score_ = value;
        onChanged();
        return this;
      }
      public Builder clearScore() {
        bitField0_ = (bitField0_ & ~0x00000001);
        score_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 catchScore = 20;
      private int catchScore_ ;
      @Override
	public boolean hasCatchScore() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      @Override
	public int getCatchScore() {
        return catchScore_;
      }
      public Builder setCatchScore(int value) {
        bitField0_ |= 0x00000002;
        catchScore_ = value;
        onChanged();
        return this;
      }
      public Builder clearCatchScore() {
        bitField0_ = (bitField0_ & ~0x00000002);
        catchScore_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:cn.mxz.protocols.user.tower.FightingRewardPro)
    }
    
    static {
      defaultInstance = new FightingRewardPro(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:cn.mxz.protocols.user.tower.FightingRewardPro)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_mxz_protocols_user_tower_TowerPro_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cn_mxz_protocols_user_tower_TowerPro_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_mxz_protocols_user_tower_TowerBugPro_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cn_mxz_protocols_user_tower_TowerBugPro_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_mxz_protocols_user_tower_FightingRewardPro_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cn_mxz_protocols_user_tower_FightingRewardPro_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\007tower.p\022\033cn.mxz.protocols.user.tower\032\013" +
      "user_base.p\"A\n\010TowerPro\0225\n\003bug\030( \001(\0132(.c" +
      "n.mxz.protocols.user.tower.TowerBugPro\"d" +
      "\n\013TowerBugPro\022\021\n\tremainSec\030( \002(\005\022\016\n\006isMi" +
      "ne\0302 \002(\010\0222\n\006finder\030< \002(\0132\".cn.mxz.protoc" +
      "ols.user.UserBasePro\"6\n\021FightingRewardPr" +
      "o\022\r\n\005score\030\n \002(\005\022\022\n\ncatchScore\030\024 \002(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        @Override
		public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_cn_mxz_protocols_user_tower_TowerPro_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_cn_mxz_protocols_user_tower_TowerPro_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_cn_mxz_protocols_user_tower_TowerPro_descriptor,
              new java.lang.String[] { "Bug", },
              cn.mxz.protocols.user.tower.TowerP.TowerPro.class,
              cn.mxz.protocols.user.tower.TowerP.TowerPro.Builder.class);
          internal_static_cn_mxz_protocols_user_tower_TowerBugPro_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_cn_mxz_protocols_user_tower_TowerBugPro_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_cn_mxz_protocols_user_tower_TowerBugPro_descriptor,
              new java.lang.String[] { "RemainSec", "IsMine", "Finder", },
              cn.mxz.protocols.user.tower.TowerP.TowerBugPro.class,
              cn.mxz.protocols.user.tower.TowerP.TowerBugPro.Builder.class);
          internal_static_cn_mxz_protocols_user_tower_FightingRewardPro_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_cn_mxz_protocols_user_tower_FightingRewardPro_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_cn_mxz_protocols_user_tower_FightingRewardPro_descriptor,
              new java.lang.String[] { "Score", "CatchScore", },
              cn.mxz.protocols.user.tower.TowerP.FightingRewardPro.class,
              cn.mxz.protocols.user.tower.TowerP.FightingRewardPro.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cn.mxz.protocols.user.UserBaseP.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
