// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vip_card.p

package cn.mxz.protocols.vip;

public final class VipCardP {
  private VipCardP() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface VipCardProOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 type = 2;
    boolean hasType();
    int getType();
    
    // required int32 remainDay = 3;
    boolean hasRemainDay();
    int getRemainDay();
    
    // required bool hasReceived = 4;
    boolean hasHasReceived();
    boolean getHasReceived();
  }
  public static final class VipCardPro extends
      com.google.protobuf.GeneratedMessage
      implements VipCardProOrBuilder {
    // Use VipCardPro.newBuilder() to construct.
    private VipCardPro(Builder builder) {
      super(builder);
    }
    private VipCardPro(boolean noInit) {}
    
    private static final VipCardPro defaultInstance;
    public static VipCardPro getDefaultInstance() {
      return defaultInstance;
    }
    
    public VipCardPro getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.mxz.protocols.vip.VipCardP.internal_static_cn_mxz_protocols_vip_VipCardPro_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.mxz.protocols.vip.VipCardP.internal_static_cn_mxz_protocols_vip_VipCardPro_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 type = 2;
    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getType() {
      return type_;
    }
    
    // required int32 remainDay = 3;
    public static final int REMAINDAY_FIELD_NUMBER = 3;
    private int remainDay_;
    public boolean hasRemainDay() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getRemainDay() {
      return remainDay_;
    }
    
    // required bool hasReceived = 4;
    public static final int HASRECEIVED_FIELD_NUMBER = 4;
    private boolean hasReceived_;
    public boolean hasHasReceived() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public boolean getHasReceived() {
      return hasReceived_;
    }
    
    private void initFields() {
      type_ = 0;
      remainDay_ = 0;
      hasReceived_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRemainDay()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHasReceived()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(2, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(3, remainDay_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(4, hasReceived_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, remainDay_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, hasReceived_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static cn.mxz.protocols.vip.VipCardP.VipCardPro parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static cn.mxz.protocols.vip.VipCardP.VipCardPro parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static cn.mxz.protocols.vip.VipCardP.VipCardPro parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static cn.mxz.protocols.vip.VipCardP.VipCardPro parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static cn.mxz.protocols.vip.VipCardP.VipCardPro parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static cn.mxz.protocols.vip.VipCardP.VipCardPro parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static cn.mxz.protocols.vip.VipCardP.VipCardPro parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static cn.mxz.protocols.vip.VipCardP.VipCardPro parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static cn.mxz.protocols.vip.VipCardP.VipCardPro parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static cn.mxz.protocols.vip.VipCardP.VipCardPro parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cn.mxz.protocols.vip.VipCardP.VipCardPro prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements cn.mxz.protocols.vip.VipCardP.VipCardProOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.mxz.protocols.vip.VipCardP.internal_static_cn_mxz_protocols_vip_VipCardPro_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.mxz.protocols.vip.VipCardP.internal_static_cn_mxz_protocols_vip_VipCardPro_fieldAccessorTable;
      }
      
      // Construct using cn.mxz.protocols.vip.VipCardP.VipCardPro.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        remainDay_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        hasReceived_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.mxz.protocols.vip.VipCardP.VipCardPro.getDescriptor();
      }
      
      public cn.mxz.protocols.vip.VipCardP.VipCardPro getDefaultInstanceForType() {
        return cn.mxz.protocols.vip.VipCardP.VipCardPro.getDefaultInstance();
      }
      
      public cn.mxz.protocols.vip.VipCardP.VipCardPro build() {
        cn.mxz.protocols.vip.VipCardP.VipCardPro result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private cn.mxz.protocols.vip.VipCardP.VipCardPro buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        cn.mxz.protocols.vip.VipCardP.VipCardPro result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public cn.mxz.protocols.vip.VipCardP.VipCardPro buildPartial() {
        cn.mxz.protocols.vip.VipCardP.VipCardPro result = new cn.mxz.protocols.vip.VipCardP.VipCardPro(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.remainDay_ = remainDay_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.hasReceived_ = hasReceived_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.mxz.protocols.vip.VipCardP.VipCardPro) {
          return mergeFrom((cn.mxz.protocols.vip.VipCardP.VipCardPro)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(cn.mxz.protocols.vip.VipCardP.VipCardPro other) {
        if (other == cn.mxz.protocols.vip.VipCardP.VipCardPro.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasRemainDay()) {
          setRemainDay(other.getRemainDay());
        }
        if (other.hasHasReceived()) {
          setHasReceived(other.getHasReceived());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!hasRemainDay()) {
          
          return false;
        }
        if (!hasHasReceived()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000001;
              type_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000002;
              remainDay_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              hasReceived_ = input.readBool();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 type = 2;
      private int type_ ;
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getType() {
        return type_;
      }
      public Builder setType(int value) {
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 remainDay = 3;
      private int remainDay_ ;
      public boolean hasRemainDay() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getRemainDay() {
        return remainDay_;
      }
      public Builder setRemainDay(int value) {
        bitField0_ |= 0x00000002;
        remainDay_ = value;
        onChanged();
        return this;
      }
      public Builder clearRemainDay() {
        bitField0_ = (bitField0_ & ~0x00000002);
        remainDay_ = 0;
        onChanged();
        return this;
      }
      
      // required bool hasReceived = 4;
      private boolean hasReceived_ ;
      public boolean hasHasReceived() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public boolean getHasReceived() {
        return hasReceived_;
      }
      public Builder setHasReceived(boolean value) {
        bitField0_ |= 0x00000004;
        hasReceived_ = value;
        onChanged();
        return this;
      }
      public Builder clearHasReceived() {
        bitField0_ = (bitField0_ & ~0x00000004);
        hasReceived_ = false;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:cn.mxz.protocols.vip.VipCardPro)
    }
    
    static {
      defaultInstance = new VipCardPro(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:cn.mxz.protocols.vip.VipCardPro)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_mxz_protocols_vip_VipCardPro_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cn_mxz_protocols_vip_VipCardPro_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nvip_card.p\022\024cn.mxz.protocols.vip\"B\n\nVi" +
      "pCardPro\022\014\n\004type\030\002 \002(\005\022\021\n\tremainDay\030\003 \002(" +
      "\005\022\023\n\013hasReceived\030\004 \002(\010"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_cn_mxz_protocols_vip_VipCardPro_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_cn_mxz_protocols_vip_VipCardPro_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_cn_mxz_protocols_vip_VipCardPro_descriptor,
              new java.lang.String[] { "Type", "RemainDay", "HasReceived", },
              cn.mxz.protocols.vip.VipCardP.VipCardPro.class,
              cn.mxz.protocols.vip.VipCardP.VipCardPro.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
