// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dogz.p

package cn.mxz.protocols.user;

public final class DogzP {
  private DogzP() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DogzListProOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .cn.mxz.protocols.user.DogzPro dogzs = 40;
    java.util.List<cn.mxz.protocols.user.DogzP.DogzPro> 
        getDogzsList();
    cn.mxz.protocols.user.DogzP.DogzPro getDogzs(int index);
    int getDogzsCount();
    java.util.List<? extends cn.mxz.protocols.user.DogzP.DogzProOrBuilder> 
        getDogzsOrBuilderList();
    cn.mxz.protocols.user.DogzP.DogzProOrBuilder getDogzsOrBuilder(
        int index);
  }
  public static final class DogzListPro extends
      com.google.protobuf.GeneratedMessage
      implements DogzListProOrBuilder {
    // Use DogzListPro.newBuilder() to construct.
    private DogzListPro(Builder builder) {
      super(builder);
    }
    private DogzListPro(boolean noInit) {}
    
    private static final DogzListPro defaultInstance;
    public static DogzListPro getDefaultInstance() {
      return defaultInstance;
    }
    
    @Override
	public DogzListPro getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.mxz.protocols.user.DogzP.internal_static_cn_mxz_protocols_user_DogzListPro_descriptor;
    }
    
    @Override
	protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.mxz.protocols.user.DogzP.internal_static_cn_mxz_protocols_user_DogzListPro_fieldAccessorTable;
    }
    
    // repeated .cn.mxz.protocols.user.DogzPro dogzs = 40;
    public static final int DOGZS_FIELD_NUMBER = 40;
    private java.util.List<cn.mxz.protocols.user.DogzP.DogzPro> dogzs_;
    @Override
	public java.util.List<cn.mxz.protocols.user.DogzP.DogzPro> getDogzsList() {
      return dogzs_;
    }
    @Override
	public java.util.List<? extends cn.mxz.protocols.user.DogzP.DogzProOrBuilder> 
        getDogzsOrBuilderList() {
      return dogzs_;
    }
    @Override
	public int getDogzsCount() {
      return dogzs_.size();
    }
    @Override
	public cn.mxz.protocols.user.DogzP.DogzPro getDogzs(int index) {
      return dogzs_.get(index);
    }
    @Override
	public cn.mxz.protocols.user.DogzP.DogzProOrBuilder getDogzsOrBuilder(
        int index) {
      return dogzs_.get(index);
    }
    
    private void initFields() {
      dogzs_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    @Override
	public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getDogzsCount(); i++) {
        if (!getDogzs(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    @Override
	public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < dogzs_.size(); i++) {
        output.writeMessage(40, dogzs_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    @Override
	public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < dogzs_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(40, dogzs_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static cn.mxz.protocols.user.DogzP.DogzListPro parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static cn.mxz.protocols.user.DogzP.DogzListPro parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static cn.mxz.protocols.user.DogzP.DogzListPro parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static cn.mxz.protocols.user.DogzP.DogzListPro parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static cn.mxz.protocols.user.DogzP.DogzListPro parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static cn.mxz.protocols.user.DogzP.DogzListPro parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static cn.mxz.protocols.user.DogzP.DogzListPro parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static cn.mxz.protocols.user.DogzP.DogzListPro parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static cn.mxz.protocols.user.DogzP.DogzListPro parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static cn.mxz.protocols.user.DogzP.DogzListPro parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    @Override
	public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cn.mxz.protocols.user.DogzP.DogzListPro prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    @Override
	public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements cn.mxz.protocols.user.DogzP.DogzListProOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.mxz.protocols.user.DogzP.internal_static_cn_mxz_protocols_user_DogzListPro_descriptor;
      }
      
      @Override
	protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.mxz.protocols.user.DogzP.internal_static_cn_mxz_protocols_user_DogzListPro_fieldAccessorTable;
      }
      
      // Construct using cn.mxz.protocols.user.DogzP.DogzListPro.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDogzsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      @Override
	public Builder clear() {
        super.clear();
        if (dogzsBuilder_ == null) {
          dogzs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          dogzsBuilder_.clear();
        }
        return this;
      }
      
      @Override
	public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      @Override
	public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.mxz.protocols.user.DogzP.DogzListPro.getDescriptor();
      }
      
      @Override
	public cn.mxz.protocols.user.DogzP.DogzListPro getDefaultInstanceForType() {
        return cn.mxz.protocols.user.DogzP.DogzListPro.getDefaultInstance();
      }
      
      @Override
	public cn.mxz.protocols.user.DogzP.DogzListPro build() {
        cn.mxz.protocols.user.DogzP.DogzListPro result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private cn.mxz.protocols.user.DogzP.DogzListPro buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        cn.mxz.protocols.user.DogzP.DogzListPro result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      @Override
	public cn.mxz.protocols.user.DogzP.DogzListPro buildPartial() {
        cn.mxz.protocols.user.DogzP.DogzListPro result = new cn.mxz.protocols.user.DogzP.DogzListPro(this);
        int from_bitField0_ = bitField0_;
        if (dogzsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            dogzs_ = java.util.Collections.unmodifiableList(dogzs_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.dogzs_ = dogzs_;
        } else {
          result.dogzs_ = dogzsBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      @Override
	public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.mxz.protocols.user.DogzP.DogzListPro) {
          return mergeFrom((cn.mxz.protocols.user.DogzP.DogzListPro)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(cn.mxz.protocols.user.DogzP.DogzListPro other) {
        if (other == cn.mxz.protocols.user.DogzP.DogzListPro.getDefaultInstance()) return this;
        if (dogzsBuilder_ == null) {
          if (!other.dogzs_.isEmpty()) {
            if (dogzs_.isEmpty()) {
              dogzs_ = other.dogzs_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDogzsIsMutable();
              dogzs_.addAll(other.dogzs_);
            }
            onChanged();
          }
        } else {
          if (!other.dogzs_.isEmpty()) {
            if (dogzsBuilder_.isEmpty()) {
              dogzsBuilder_.dispose();
              dogzsBuilder_ = null;
              dogzs_ = other.dogzs_;
              bitField0_ = (bitField0_ & ~0x00000001);
              dogzsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getDogzsFieldBuilder() : null;
            } else {
              dogzsBuilder_.addAllMessages(other.dogzs_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      @Override
	public final boolean isInitialized() {
        for (int i = 0; i < getDogzsCount(); i++) {
          if (!getDogzs(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      @Override
	public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 322: {
              cn.mxz.protocols.user.DogzP.DogzPro.Builder subBuilder = cn.mxz.protocols.user.DogzP.DogzPro.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addDogzs(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .cn.mxz.protocols.user.DogzPro dogzs = 40;
      private java.util.List<cn.mxz.protocols.user.DogzP.DogzPro> dogzs_ =
        java.util.Collections.emptyList();
      private void ensureDogzsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          dogzs_ = new java.util.ArrayList<cn.mxz.protocols.user.DogzP.DogzPro>(dogzs_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          cn.mxz.protocols.user.DogzP.DogzPro, cn.mxz.protocols.user.DogzP.DogzPro.Builder, cn.mxz.protocols.user.DogzP.DogzProOrBuilder> dogzsBuilder_;
      
      @Override
	public java.util.List<cn.mxz.protocols.user.DogzP.DogzPro> getDogzsList() {
        if (dogzsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(dogzs_);
        } else {
          return dogzsBuilder_.getMessageList();
        }
      }
      @Override
	public int getDogzsCount() {
        if (dogzsBuilder_ == null) {
          return dogzs_.size();
        } else {
          return dogzsBuilder_.getCount();
        }
      }
      @Override
	public cn.mxz.protocols.user.DogzP.DogzPro getDogzs(int index) {
        if (dogzsBuilder_ == null) {
          return dogzs_.get(index);
        } else {
          return dogzsBuilder_.getMessage(index);
        }
      }
      public Builder setDogzs(
          int index, cn.mxz.protocols.user.DogzP.DogzPro value) {
        if (dogzsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDogzsIsMutable();
          dogzs_.set(index, value);
          onChanged();
        } else {
          dogzsBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setDogzs(
          int index, cn.mxz.protocols.user.DogzP.DogzPro.Builder builderForValue) {
        if (dogzsBuilder_ == null) {
          ensureDogzsIsMutable();
          dogzs_.set(index, builderForValue.build());
          onChanged();
        } else {
          dogzsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addDogzs(cn.mxz.protocols.user.DogzP.DogzPro value) {
        if (dogzsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDogzsIsMutable();
          dogzs_.add(value);
          onChanged();
        } else {
          dogzsBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addDogzs(
          int index, cn.mxz.protocols.user.DogzP.DogzPro value) {
        if (dogzsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDogzsIsMutable();
          dogzs_.add(index, value);
          onChanged();
        } else {
          dogzsBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addDogzs(
          cn.mxz.protocols.user.DogzP.DogzPro.Builder builderForValue) {
        if (dogzsBuilder_ == null) {
          ensureDogzsIsMutable();
          dogzs_.add(builderForValue.build());
          onChanged();
        } else {
          dogzsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addDogzs(
          int index, cn.mxz.protocols.user.DogzP.DogzPro.Builder builderForValue) {
        if (dogzsBuilder_ == null) {
          ensureDogzsIsMutable();
          dogzs_.add(index, builderForValue.build());
          onChanged();
        } else {
          dogzsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllDogzs(
          java.lang.Iterable<? extends cn.mxz.protocols.user.DogzP.DogzPro> values) {
        if (dogzsBuilder_ == null) {
          ensureDogzsIsMutable();
          super.addAll(values, dogzs_);
          onChanged();
        } else {
          dogzsBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearDogzs() {
        if (dogzsBuilder_ == null) {
          dogzs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          dogzsBuilder_.clear();
        }
        return this;
      }
      public Builder removeDogzs(int index) {
        if (dogzsBuilder_ == null) {
          ensureDogzsIsMutable();
          dogzs_.remove(index);
          onChanged();
        } else {
          dogzsBuilder_.remove(index);
        }
        return this;
      }
      public cn.mxz.protocols.user.DogzP.DogzPro.Builder getDogzsBuilder(
          int index) {
        return getDogzsFieldBuilder().getBuilder(index);
      }
      @Override
	public cn.mxz.protocols.user.DogzP.DogzProOrBuilder getDogzsOrBuilder(
          int index) {
        if (dogzsBuilder_ == null) {
          return dogzs_.get(index);  } else {
          return dogzsBuilder_.getMessageOrBuilder(index);
        }
      }
      @Override
	public java.util.List<? extends cn.mxz.protocols.user.DogzP.DogzProOrBuilder> 
           getDogzsOrBuilderList() {
        if (dogzsBuilder_ != null) {
          return dogzsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(dogzs_);
        }
      }
      public cn.mxz.protocols.user.DogzP.DogzPro.Builder addDogzsBuilder() {
        return getDogzsFieldBuilder().addBuilder(
            cn.mxz.protocols.user.DogzP.DogzPro.getDefaultInstance());
      }
      public cn.mxz.protocols.user.DogzP.DogzPro.Builder addDogzsBuilder(
          int index) {
        return getDogzsFieldBuilder().addBuilder(
            index, cn.mxz.protocols.user.DogzP.DogzPro.getDefaultInstance());
      }
      public java.util.List<cn.mxz.protocols.user.DogzP.DogzPro.Builder> 
           getDogzsBuilderList() {
        return getDogzsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          cn.mxz.protocols.user.DogzP.DogzPro, cn.mxz.protocols.user.DogzP.DogzPro.Builder, cn.mxz.protocols.user.DogzP.DogzProOrBuilder> 
          getDogzsFieldBuilder() {
        if (dogzsBuilder_ == null) {
          dogzsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              cn.mxz.protocols.user.DogzP.DogzPro, cn.mxz.protocols.user.DogzP.DogzPro.Builder, cn.mxz.protocols.user.DogzP.DogzProOrBuilder>(
                  dogzs_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          dogzs_ = null;
        }
        return dogzsBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:cn.mxz.protocols.user.DogzListPro)
    }
    
    static {
      defaultInstance = new DogzListPro(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:cn.mxz.protocols.user.DogzListPro)
  }
  
  public interface DogzProOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 typeId = 10;
    boolean hasTypeId();
    int getTypeId();
    
    // required bool isFighting = 21;
    boolean hasIsFighting();
    boolean getIsFighting();
    
    // required int32 level = 30;
    boolean hasLevel();
    int getLevel();
    
    // required int32 step = 50;
    boolean hasStep();
    int getStep();
    
    // required .cn.mxz.protocols.user.FractionPro growth = 60;
    boolean hasGrowth();
    cn.mxz.protocols.user.FractionP.FractionPro getGrowth();
    cn.mxz.protocols.user.FractionP.FractionProOrBuilder getGrowthOrBuilder();
    
    // required bool isProtected = 61;
    boolean hasIsProtected();
    boolean getIsProtected();
    
    // required int32 dunWuTimes = 90;
    boolean hasDunWuTimes();
    int getDunWuTimes();
    
    // required int32 fishCount = 100;
    boolean hasFishCount();
    int getFishCount();
    
    // required int32 huiHunDanCount = 110;
    boolean hasHuiHunDanCount();
    int getHuiHunDanCount();
    
    // required int32 protectProp = 120;
    boolean hasProtectProp();
    int getProtectProp();
    
    // required .cn.mxz.protocols.user.DogzSkillPro skill = 130;
    boolean hasSkill();
    cn.mxz.protocols.user.DogzP.DogzSkillPro getSkill();
    cn.mxz.protocols.user.DogzP.DogzSkillProOrBuilder getSkillOrBuilder();
  }
  public static final class DogzPro extends
      com.google.protobuf.GeneratedMessage
      implements DogzProOrBuilder {
    // Use DogzPro.newBuilder() to construct.
    private DogzPro(Builder builder) {
      super(builder);
    }
    private DogzPro(boolean noInit) {}
    
    private static final DogzPro defaultInstance;
    public static DogzPro getDefaultInstance() {
      return defaultInstance;
    }
    
    @Override
	public DogzPro getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.mxz.protocols.user.DogzP.internal_static_cn_mxz_protocols_user_DogzPro_descriptor;
    }
    
    @Override
	protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.mxz.protocols.user.DogzP.internal_static_cn_mxz_protocols_user_DogzPro_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 typeId = 10;
    public static final int TYPEID_FIELD_NUMBER = 10;
    private int typeId_;
    @Override
	public boolean hasTypeId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    @Override
	public int getTypeId() {
      return typeId_;
    }
    
    // required bool isFighting = 21;
    public static final int ISFIGHTING_FIELD_NUMBER = 21;
    private boolean isFighting_;
    @Override
	public boolean hasIsFighting() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    @Override
	public boolean getIsFighting() {
      return isFighting_;
    }
    
    // required int32 level = 30;
    public static final int LEVEL_FIELD_NUMBER = 30;
    private int level_;
    @Override
	public boolean hasLevel() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    @Override
	public int getLevel() {
      return level_;
    }
    
    // required int32 step = 50;
    public static final int STEP_FIELD_NUMBER = 50;
    private int step_;
    @Override
	public boolean hasStep() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    @Override
	public int getStep() {
      return step_;
    }
    
    // required .cn.mxz.protocols.user.FractionPro growth = 60;
    public static final int GROWTH_FIELD_NUMBER = 60;
    private cn.mxz.protocols.user.FractionP.FractionPro growth_;
    @Override
	public boolean hasGrowth() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    @Override
	public cn.mxz.protocols.user.FractionP.FractionPro getGrowth() {
      return growth_;
    }
    @Override
	public cn.mxz.protocols.user.FractionP.FractionProOrBuilder getGrowthOrBuilder() {
      return growth_;
    }
    
    // required bool isProtected = 61;
    public static final int ISPROTECTED_FIELD_NUMBER = 61;
    private boolean isProtected_;
    @Override
	public boolean hasIsProtected() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    @Override
	public boolean getIsProtected() {
      return isProtected_;
    }
    
    // required int32 dunWuTimes = 90;
    public static final int DUNWUTIMES_FIELD_NUMBER = 90;
    private int dunWuTimes_;
    @Override
	public boolean hasDunWuTimes() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    @Override
	public int getDunWuTimes() {
      return dunWuTimes_;
    }
    
    // required int32 fishCount = 100;
    public static final int FISHCOUNT_FIELD_NUMBER = 100;
    private int fishCount_;
    @Override
	public boolean hasFishCount() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    @Override
	public int getFishCount() {
      return fishCount_;
    }
    
    // required int32 huiHunDanCount = 110;
    public static final int HUIHUNDANCOUNT_FIELD_NUMBER = 110;
    private int huiHunDanCount_;
    @Override
	public boolean hasHuiHunDanCount() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    @Override
	public int getHuiHunDanCount() {
      return huiHunDanCount_;
    }
    
    // required int32 protectProp = 120;
    public static final int PROTECTPROP_FIELD_NUMBER = 120;
    private int protectProp_;
    @Override
	public boolean hasProtectProp() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    @Override
	public int getProtectProp() {
      return protectProp_;
    }
    
    // required .cn.mxz.protocols.user.DogzSkillPro skill = 130;
    public static final int SKILL_FIELD_NUMBER = 130;
    private cn.mxz.protocols.user.DogzP.DogzSkillPro skill_;
    @Override
	public boolean hasSkill() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    @Override
	public cn.mxz.protocols.user.DogzP.DogzSkillPro getSkill() {
      return skill_;
    }
    @Override
	public cn.mxz.protocols.user.DogzP.DogzSkillProOrBuilder getSkillOrBuilder() {
      return skill_;
    }
    
    private void initFields() {
      typeId_ = 0;
      isFighting_ = false;
      level_ = 0;
      step_ = 0;
      growth_ = cn.mxz.protocols.user.FractionP.FractionPro.getDefaultInstance();
      isProtected_ = false;
      dunWuTimes_ = 0;
      fishCount_ = 0;
      huiHunDanCount_ = 0;
      protectProp_ = 0;
      skill_ = cn.mxz.protocols.user.DogzP.DogzSkillPro.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    @Override
	public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasTypeId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIsFighting()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLevel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStep()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasGrowth()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIsProtected()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDunWuTimes()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFishCount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHuiHunDanCount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasProtectProp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSkill()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getGrowth().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getSkill().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    @Override
	public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(10, typeId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(21, isFighting_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(30, level_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(50, step_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(60, growth_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBool(61, isProtected_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(90, dunWuTimes_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(100, fishCount_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt32(110, huiHunDanCount_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeInt32(120, protectProp_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeMessage(130, skill_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    @Override
	public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, typeId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(21, isFighting_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(30, level_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(50, step_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(60, growth_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(61, isProtected_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(90, dunWuTimes_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(100, fishCount_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(110, huiHunDanCount_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(120, protectProp_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(130, skill_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static cn.mxz.protocols.user.DogzP.DogzPro parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static cn.mxz.protocols.user.DogzP.DogzPro parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static cn.mxz.protocols.user.DogzP.DogzPro parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static cn.mxz.protocols.user.DogzP.DogzPro parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static cn.mxz.protocols.user.DogzP.DogzPro parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static cn.mxz.protocols.user.DogzP.DogzPro parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static cn.mxz.protocols.user.DogzP.DogzPro parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static cn.mxz.protocols.user.DogzP.DogzPro parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static cn.mxz.protocols.user.DogzP.DogzPro parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static cn.mxz.protocols.user.DogzP.DogzPro parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    @Override
	public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cn.mxz.protocols.user.DogzP.DogzPro prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    @Override
	public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements cn.mxz.protocols.user.DogzP.DogzProOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.mxz.protocols.user.DogzP.internal_static_cn_mxz_protocols_user_DogzPro_descriptor;
      }
      
      @Override
	protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.mxz.protocols.user.DogzP.internal_static_cn_mxz_protocols_user_DogzPro_fieldAccessorTable;
      }
      
      // Construct using cn.mxz.protocols.user.DogzP.DogzPro.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getGrowthFieldBuilder();
          getSkillFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      @Override
	public Builder clear() {
        super.clear();
        typeId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        isFighting_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        level_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        step_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        if (growthBuilder_ == null) {
          growth_ = cn.mxz.protocols.user.FractionP.FractionPro.getDefaultInstance();
        } else {
          growthBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        isProtected_ = false;
        bitField0_ = (bitField0_ & ~0x00000020);
        dunWuTimes_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        fishCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        huiHunDanCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        protectProp_ = 0;
        bitField0_ = (bitField0_ & ~0x00000200);
        if (skillBuilder_ == null) {
          skill_ = cn.mxz.protocols.user.DogzP.DogzSkillPro.getDefaultInstance();
        } else {
          skillBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000400);
        return this;
      }
      
      @Override
	public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      @Override
	public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.mxz.protocols.user.DogzP.DogzPro.getDescriptor();
      }
      
      @Override
	public cn.mxz.protocols.user.DogzP.DogzPro getDefaultInstanceForType() {
        return cn.mxz.protocols.user.DogzP.DogzPro.getDefaultInstance();
      }
      
      @Override
	public cn.mxz.protocols.user.DogzP.DogzPro build() {
        cn.mxz.protocols.user.DogzP.DogzPro result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private cn.mxz.protocols.user.DogzP.DogzPro buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        cn.mxz.protocols.user.DogzP.DogzPro result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      @Override
	public cn.mxz.protocols.user.DogzP.DogzPro buildPartial() {
        cn.mxz.protocols.user.DogzP.DogzPro result = new cn.mxz.protocols.user.DogzP.DogzPro(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.typeId_ = typeId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.isFighting_ = isFighting_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.level_ = level_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.step_ = step_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        if (growthBuilder_ == null) {
          result.growth_ = growth_;
        } else {
          result.growth_ = growthBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.isProtected_ = isProtected_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.dunWuTimes_ = dunWuTimes_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.fishCount_ = fishCount_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.huiHunDanCount_ = huiHunDanCount_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.protectProp_ = protectProp_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        if (skillBuilder_ == null) {
          result.skill_ = skill_;
        } else {
          result.skill_ = skillBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      @Override
	public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.mxz.protocols.user.DogzP.DogzPro) {
          return mergeFrom((cn.mxz.protocols.user.DogzP.DogzPro)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(cn.mxz.protocols.user.DogzP.DogzPro other) {
        if (other == cn.mxz.protocols.user.DogzP.DogzPro.getDefaultInstance()) return this;
        if (other.hasTypeId()) {
          setTypeId(other.getTypeId());
        }
        if (other.hasIsFighting()) {
          setIsFighting(other.getIsFighting());
        }
        if (other.hasLevel()) {
          setLevel(other.getLevel());
        }
        if (other.hasStep()) {
          setStep(other.getStep());
        }
        if (other.hasGrowth()) {
          mergeGrowth(other.getGrowth());
        }
        if (other.hasIsProtected()) {
          setIsProtected(other.getIsProtected());
        }
        if (other.hasDunWuTimes()) {
          setDunWuTimes(other.getDunWuTimes());
        }
        if (other.hasFishCount()) {
          setFishCount(other.getFishCount());
        }
        if (other.hasHuiHunDanCount()) {
          setHuiHunDanCount(other.getHuiHunDanCount());
        }
        if (other.hasProtectProp()) {
          setProtectProp(other.getProtectProp());
        }
        if (other.hasSkill()) {
          mergeSkill(other.getSkill());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      @Override
	public final boolean isInitialized() {
        if (!hasTypeId()) {
          
          return false;
        }
        if (!hasIsFighting()) {
          
          return false;
        }
        if (!hasLevel()) {
          
          return false;
        }
        if (!hasStep()) {
          
          return false;
        }
        if (!hasGrowth()) {
          
          return false;
        }
        if (!hasIsProtected()) {
          
          return false;
        }
        if (!hasDunWuTimes()) {
          
          return false;
        }
        if (!hasFishCount()) {
          
          return false;
        }
        if (!hasHuiHunDanCount()) {
          
          return false;
        }
        if (!hasProtectProp()) {
          
          return false;
        }
        if (!hasSkill()) {
          
          return false;
        }
        if (!getGrowth().isInitialized()) {
          
          return false;
        }
        if (!getSkill().isInitialized()) {
          
          return false;
        }
        return true;
      }
      
      @Override
	public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 80: {
              bitField0_ |= 0x00000001;
              typeId_ = input.readInt32();
              break;
            }
            case 168: {
              bitField0_ |= 0x00000002;
              isFighting_ = input.readBool();
              break;
            }
            case 240: {
              bitField0_ |= 0x00000004;
              level_ = input.readInt32();
              break;
            }
            case 400: {
              bitField0_ |= 0x00000008;
              step_ = input.readInt32();
              break;
            }
            case 482: {
              cn.mxz.protocols.user.FractionP.FractionPro.Builder subBuilder = cn.mxz.protocols.user.FractionP.FractionPro.newBuilder();
              if (hasGrowth()) {
                subBuilder.mergeFrom(getGrowth());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setGrowth(subBuilder.buildPartial());
              break;
            }
            case 488: {
              bitField0_ |= 0x00000020;
              isProtected_ = input.readBool();
              break;
            }
            case 720: {
              bitField0_ |= 0x00000040;
              dunWuTimes_ = input.readInt32();
              break;
            }
            case 800: {
              bitField0_ |= 0x00000080;
              fishCount_ = input.readInt32();
              break;
            }
            case 880: {
              bitField0_ |= 0x00000100;
              huiHunDanCount_ = input.readInt32();
              break;
            }
            case 960: {
              bitField0_ |= 0x00000200;
              protectProp_ = input.readInt32();
              break;
            }
            case 1042: {
              cn.mxz.protocols.user.DogzP.DogzSkillPro.Builder subBuilder = cn.mxz.protocols.user.DogzP.DogzSkillPro.newBuilder();
              if (hasSkill()) {
                subBuilder.mergeFrom(getSkill());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setSkill(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 typeId = 10;
      private int typeId_ ;
      @Override
	public boolean hasTypeId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      @Override
	public int getTypeId() {
        return typeId_;
      }
      public Builder setTypeId(int value) {
        bitField0_ |= 0x00000001;
        typeId_ = value;
        onChanged();
        return this;
      }
      public Builder clearTypeId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        typeId_ = 0;
        onChanged();
        return this;
      }
      
      // required bool isFighting = 21;
      private boolean isFighting_ ;
      @Override
	public boolean hasIsFighting() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      @Override
	public boolean getIsFighting() {
        return isFighting_;
      }
      public Builder setIsFighting(boolean value) {
        bitField0_ |= 0x00000002;
        isFighting_ = value;
        onChanged();
        return this;
      }
      public Builder clearIsFighting() {
        bitField0_ = (bitField0_ & ~0x00000002);
        isFighting_ = false;
        onChanged();
        return this;
      }
      
      // required int32 level = 30;
      private int level_ ;
      @Override
	public boolean hasLevel() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      @Override
	public int getLevel() {
        return level_;
      }
      public Builder setLevel(int value) {
        bitField0_ |= 0x00000004;
        level_ = value;
        onChanged();
        return this;
      }
      public Builder clearLevel() {
        bitField0_ = (bitField0_ & ~0x00000004);
        level_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 step = 50;
      private int step_ ;
      @Override
	public boolean hasStep() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      @Override
	public int getStep() {
        return step_;
      }
      public Builder setStep(int value) {
        bitField0_ |= 0x00000008;
        step_ = value;
        onChanged();
        return this;
      }
      public Builder clearStep() {
        bitField0_ = (bitField0_ & ~0x00000008);
        step_ = 0;
        onChanged();
        return this;
      }
      
      // required .cn.mxz.protocols.user.FractionPro growth = 60;
      private cn.mxz.protocols.user.FractionP.FractionPro growth_ = cn.mxz.protocols.user.FractionP.FractionPro.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          cn.mxz.protocols.user.FractionP.FractionPro, cn.mxz.protocols.user.FractionP.FractionPro.Builder, cn.mxz.protocols.user.FractionP.FractionProOrBuilder> growthBuilder_;
      @Override
	public boolean hasGrowth() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      @Override
	public cn.mxz.protocols.user.FractionP.FractionPro getGrowth() {
        if (growthBuilder_ == null) {
          return growth_;
        } else {
          return growthBuilder_.getMessage();
        }
      }
      public Builder setGrowth(cn.mxz.protocols.user.FractionP.FractionPro value) {
        if (growthBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          growth_ = value;
          onChanged();
        } else {
          growthBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      public Builder setGrowth(
          cn.mxz.protocols.user.FractionP.FractionPro.Builder builderForValue) {
        if (growthBuilder_ == null) {
          growth_ = builderForValue.build();
          onChanged();
        } else {
          growthBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      public Builder mergeGrowth(cn.mxz.protocols.user.FractionP.FractionPro value) {
        if (growthBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              growth_ != cn.mxz.protocols.user.FractionP.FractionPro.getDefaultInstance()) {
            growth_ =
              cn.mxz.protocols.user.FractionP.FractionPro.newBuilder(growth_).mergeFrom(value).buildPartial();
          } else {
            growth_ = value;
          }
          onChanged();
        } else {
          growthBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      public Builder clearGrowth() {
        if (growthBuilder_ == null) {
          growth_ = cn.mxz.protocols.user.FractionP.FractionPro.getDefaultInstance();
          onChanged();
        } else {
          growthBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      public cn.mxz.protocols.user.FractionP.FractionPro.Builder getGrowthBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getGrowthFieldBuilder().getBuilder();
      }
      @Override
	public cn.mxz.protocols.user.FractionP.FractionProOrBuilder getGrowthOrBuilder() {
        if (growthBuilder_ != null) {
          return growthBuilder_.getMessageOrBuilder();
        } else {
          return growth_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          cn.mxz.protocols.user.FractionP.FractionPro, cn.mxz.protocols.user.FractionP.FractionPro.Builder, cn.mxz.protocols.user.FractionP.FractionProOrBuilder> 
          getGrowthFieldBuilder() {
        if (growthBuilder_ == null) {
          growthBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              cn.mxz.protocols.user.FractionP.FractionPro, cn.mxz.protocols.user.FractionP.FractionPro.Builder, cn.mxz.protocols.user.FractionP.FractionProOrBuilder>(
                  growth_,
                  getParentForChildren(),
                  isClean());
          growth_ = null;
        }
        return growthBuilder_;
      }
      
      // required bool isProtected = 61;
      private boolean isProtected_ ;
      @Override
	public boolean hasIsProtected() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      @Override
	public boolean getIsProtected() {
        return isProtected_;
      }
      public Builder setIsProtected(boolean value) {
        bitField0_ |= 0x00000020;
        isProtected_ = value;
        onChanged();
        return this;
      }
      public Builder clearIsProtected() {
        bitField0_ = (bitField0_ & ~0x00000020);
        isProtected_ = false;
        onChanged();
        return this;
      }
      
      // required int32 dunWuTimes = 90;
      private int dunWuTimes_ ;
      @Override
	public boolean hasDunWuTimes() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      @Override
	public int getDunWuTimes() {
        return dunWuTimes_;
      }
      public Builder setDunWuTimes(int value) {
        bitField0_ |= 0x00000040;
        dunWuTimes_ = value;
        onChanged();
        return this;
      }
      public Builder clearDunWuTimes() {
        bitField0_ = (bitField0_ & ~0x00000040);
        dunWuTimes_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 fishCount = 100;
      private int fishCount_ ;
      @Override
	public boolean hasFishCount() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      @Override
	public int getFishCount() {
        return fishCount_;
      }
      public Builder setFishCount(int value) {
        bitField0_ |= 0x00000080;
        fishCount_ = value;
        onChanged();
        return this;
      }
      public Builder clearFishCount() {
        bitField0_ = (bitField0_ & ~0x00000080);
        fishCount_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 huiHunDanCount = 110;
      private int huiHunDanCount_ ;
      @Override
	public boolean hasHuiHunDanCount() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      @Override
	public int getHuiHunDanCount() {
        return huiHunDanCount_;
      }
      public Builder setHuiHunDanCount(int value) {
        bitField0_ |= 0x00000100;
        huiHunDanCount_ = value;
        onChanged();
        return this;
      }
      public Builder clearHuiHunDanCount() {
        bitField0_ = (bitField0_ & ~0x00000100);
        huiHunDanCount_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 protectProp = 120;
      private int protectProp_ ;
      @Override
	public boolean hasProtectProp() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      @Override
	public int getProtectProp() {
        return protectProp_;
      }
      public Builder setProtectProp(int value) {
        bitField0_ |= 0x00000200;
        protectProp_ = value;
        onChanged();
        return this;
      }
      public Builder clearProtectProp() {
        bitField0_ = (bitField0_ & ~0x00000200);
        protectProp_ = 0;
        onChanged();
        return this;
      }
      
      // required .cn.mxz.protocols.user.DogzSkillPro skill = 130;
      private cn.mxz.protocols.user.DogzP.DogzSkillPro skill_ = cn.mxz.protocols.user.DogzP.DogzSkillPro.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          cn.mxz.protocols.user.DogzP.DogzSkillPro, cn.mxz.protocols.user.DogzP.DogzSkillPro.Builder, cn.mxz.protocols.user.DogzP.DogzSkillProOrBuilder> skillBuilder_;
      @Override
	public boolean hasSkill() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      @Override
	public cn.mxz.protocols.user.DogzP.DogzSkillPro getSkill() {
        if (skillBuilder_ == null) {
          return skill_;
        } else {
          return skillBuilder_.getMessage();
        }
      }
      public Builder setSkill(cn.mxz.protocols.user.DogzP.DogzSkillPro value) {
        if (skillBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          skill_ = value;
          onChanged();
        } else {
          skillBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000400;
        return this;
      }
      public Builder setSkill(
          cn.mxz.protocols.user.DogzP.DogzSkillPro.Builder builderForValue) {
        if (skillBuilder_ == null) {
          skill_ = builderForValue.build();
          onChanged();
        } else {
          skillBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000400;
        return this;
      }
      public Builder mergeSkill(cn.mxz.protocols.user.DogzP.DogzSkillPro value) {
        if (skillBuilder_ == null) {
          if (((bitField0_ & 0x00000400) == 0x00000400) &&
              skill_ != cn.mxz.protocols.user.DogzP.DogzSkillPro.getDefaultInstance()) {
            skill_ =
              cn.mxz.protocols.user.DogzP.DogzSkillPro.newBuilder(skill_).mergeFrom(value).buildPartial();
          } else {
            skill_ = value;
          }
          onChanged();
        } else {
          skillBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000400;
        return this;
      }
      public Builder clearSkill() {
        if (skillBuilder_ == null) {
          skill_ = cn.mxz.protocols.user.DogzP.DogzSkillPro.getDefaultInstance();
          onChanged();
        } else {
          skillBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000400);
        return this;
      }
      public cn.mxz.protocols.user.DogzP.DogzSkillPro.Builder getSkillBuilder() {
        bitField0_ |= 0x00000400;
        onChanged();
        return getSkillFieldBuilder().getBuilder();
      }
      @Override
	public cn.mxz.protocols.user.DogzP.DogzSkillProOrBuilder getSkillOrBuilder() {
        if (skillBuilder_ != null) {
          return skillBuilder_.getMessageOrBuilder();
        } else {
          return skill_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          cn.mxz.protocols.user.DogzP.DogzSkillPro, cn.mxz.protocols.user.DogzP.DogzSkillPro.Builder, cn.mxz.protocols.user.DogzP.DogzSkillProOrBuilder> 
          getSkillFieldBuilder() {
        if (skillBuilder_ == null) {
          skillBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              cn.mxz.protocols.user.DogzP.DogzSkillPro, cn.mxz.protocols.user.DogzP.DogzSkillPro.Builder, cn.mxz.protocols.user.DogzP.DogzSkillProOrBuilder>(
                  skill_,
                  getParentForChildren(),
                  isClean());
          skill_ = null;
        }
        return skillBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:cn.mxz.protocols.user.DogzPro)
    }
    
    static {
      defaultInstance = new DogzPro(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:cn.mxz.protocols.user.DogzPro)
  }
  
  public interface DogzSkillProOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 id = 120;
    boolean hasId();
    int getId();
    
    // required int32 skillAddition = 140;
    boolean hasSkillAddition();
    int getSkillAddition();
    
    // required int32 skillProbability = 150;
    boolean hasSkillProbability();
    int getSkillProbability();
  }
  public static final class DogzSkillPro extends
      com.google.protobuf.GeneratedMessage
      implements DogzSkillProOrBuilder {
    // Use DogzSkillPro.newBuilder() to construct.
    private DogzSkillPro(Builder builder) {
      super(builder);
    }
    private DogzSkillPro(boolean noInit) {}
    
    private static final DogzSkillPro defaultInstance;
    public static DogzSkillPro getDefaultInstance() {
      return defaultInstance;
    }
    
    @Override
	public DogzSkillPro getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.mxz.protocols.user.DogzP.internal_static_cn_mxz_protocols_user_DogzSkillPro_descriptor;
    }
    
    @Override
	protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.mxz.protocols.user.DogzP.internal_static_cn_mxz_protocols_user_DogzSkillPro_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 id = 120;
    public static final int ID_FIELD_NUMBER = 120;
    private int id_;
    @Override
	public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    @Override
	public int getId() {
      return id_;
    }
    
    // required int32 skillAddition = 140;
    public static final int SKILLADDITION_FIELD_NUMBER = 140;
    private int skillAddition_;
    @Override
	public boolean hasSkillAddition() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    @Override
	public int getSkillAddition() {
      return skillAddition_;
    }
    
    // required int32 skillProbability = 150;
    public static final int SKILLPROBABILITY_FIELD_NUMBER = 150;
    private int skillProbability_;
    @Override
	public boolean hasSkillProbability() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    @Override
	public int getSkillProbability() {
      return skillProbability_;
    }
    
    private void initFields() {
      id_ = 0;
      skillAddition_ = 0;
      skillProbability_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    @Override
	public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSkillAddition()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSkillProbability()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    @Override
	public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(120, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(140, skillAddition_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(150, skillProbability_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    @Override
	public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(120, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(140, skillAddition_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(150, skillProbability_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static cn.mxz.protocols.user.DogzP.DogzSkillPro parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static cn.mxz.protocols.user.DogzP.DogzSkillPro parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static cn.mxz.protocols.user.DogzP.DogzSkillPro parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static cn.mxz.protocols.user.DogzP.DogzSkillPro parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static cn.mxz.protocols.user.DogzP.DogzSkillPro parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static cn.mxz.protocols.user.DogzP.DogzSkillPro parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static cn.mxz.protocols.user.DogzP.DogzSkillPro parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static cn.mxz.protocols.user.DogzP.DogzSkillPro parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static cn.mxz.protocols.user.DogzP.DogzSkillPro parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static cn.mxz.protocols.user.DogzP.DogzSkillPro parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    @Override
	public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cn.mxz.protocols.user.DogzP.DogzSkillPro prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    @Override
	public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements cn.mxz.protocols.user.DogzP.DogzSkillProOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.mxz.protocols.user.DogzP.internal_static_cn_mxz_protocols_user_DogzSkillPro_descriptor;
      }
      
      @Override
	protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.mxz.protocols.user.DogzP.internal_static_cn_mxz_protocols_user_DogzSkillPro_fieldAccessorTable;
      }
      
      // Construct using cn.mxz.protocols.user.DogzP.DogzSkillPro.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      @Override
	public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        skillAddition_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        skillProbability_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      @Override
	public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      @Override
	public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.mxz.protocols.user.DogzP.DogzSkillPro.getDescriptor();
      }
      
      @Override
	public cn.mxz.protocols.user.DogzP.DogzSkillPro getDefaultInstanceForType() {
        return cn.mxz.protocols.user.DogzP.DogzSkillPro.getDefaultInstance();
      }
      
      @Override
	public cn.mxz.protocols.user.DogzP.DogzSkillPro build() {
        cn.mxz.protocols.user.DogzP.DogzSkillPro result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private cn.mxz.protocols.user.DogzP.DogzSkillPro buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        cn.mxz.protocols.user.DogzP.DogzSkillPro result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      @Override
	public cn.mxz.protocols.user.DogzP.DogzSkillPro buildPartial() {
        cn.mxz.protocols.user.DogzP.DogzSkillPro result = new cn.mxz.protocols.user.DogzP.DogzSkillPro(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.skillAddition_ = skillAddition_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.skillProbability_ = skillProbability_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      @Override
	public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.mxz.protocols.user.DogzP.DogzSkillPro) {
          return mergeFrom((cn.mxz.protocols.user.DogzP.DogzSkillPro)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(cn.mxz.protocols.user.DogzP.DogzSkillPro other) {
        if (other == cn.mxz.protocols.user.DogzP.DogzSkillPro.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasSkillAddition()) {
          setSkillAddition(other.getSkillAddition());
        }
        if (other.hasSkillProbability()) {
          setSkillProbability(other.getSkillProbability());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      @Override
	public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasSkillAddition()) {
          
          return false;
        }
        if (!hasSkillProbability()) {
          
          return false;
        }
        return true;
      }
      
      @Override
	public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 960: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 1120: {
              bitField0_ |= 0x00000002;
              skillAddition_ = input.readInt32();
              break;
            }
            case 1200: {
              bitField0_ |= 0x00000004;
              skillProbability_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 id = 120;
      private int id_ ;
      @Override
	public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      @Override
	public int getId() {
        return id_;
      }
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 skillAddition = 140;
      private int skillAddition_ ;
      @Override
	public boolean hasSkillAddition() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      @Override
	public int getSkillAddition() {
        return skillAddition_;
      }
      public Builder setSkillAddition(int value) {
        bitField0_ |= 0x00000002;
        skillAddition_ = value;
        onChanged();
        return this;
      }
      public Builder clearSkillAddition() {
        bitField0_ = (bitField0_ & ~0x00000002);
        skillAddition_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 skillProbability = 150;
      private int skillProbability_ ;
      @Override
	public boolean hasSkillProbability() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      @Override
	public int getSkillProbability() {
        return skillProbability_;
      }
      public Builder setSkillProbability(int value) {
        bitField0_ |= 0x00000004;
        skillProbability_ = value;
        onChanged();
        return this;
      }
      public Builder clearSkillProbability() {
        bitField0_ = (bitField0_ & ~0x00000004);
        skillProbability_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:cn.mxz.protocols.user.DogzSkillPro)
    }
    
    static {
      defaultInstance = new DogzSkillPro(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:cn.mxz.protocols.user.DogzSkillPro)
  }
  
  public interface DogzFightingOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional .cn.mxz.protocols.user.DogzPro dogz = 10;
    boolean hasDogz();
    cn.mxz.protocols.user.DogzP.DogzPro getDogz();
    cn.mxz.protocols.user.DogzP.DogzProOrBuilder getDogzOrBuilder();
  }
  public static final class DogzFighting extends
      com.google.protobuf.GeneratedMessage
      implements DogzFightingOrBuilder {
    // Use DogzFighting.newBuilder() to construct.
    private DogzFighting(Builder builder) {
      super(builder);
    }
    private DogzFighting(boolean noInit) {}
    
    private static final DogzFighting defaultInstance;
    public static DogzFighting getDefaultInstance() {
      return defaultInstance;
    }
    
    @Override
	public DogzFighting getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.mxz.protocols.user.DogzP.internal_static_cn_mxz_protocols_user_DogzFighting_descriptor;
    }
    
    @Override
	protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.mxz.protocols.user.DogzP.internal_static_cn_mxz_protocols_user_DogzFighting_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional .cn.mxz.protocols.user.DogzPro dogz = 10;
    public static final int DOGZ_FIELD_NUMBER = 10;
    private cn.mxz.protocols.user.DogzP.DogzPro dogz_;
    @Override
	public boolean hasDogz() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    @Override
	public cn.mxz.protocols.user.DogzP.DogzPro getDogz() {
      return dogz_;
    }
    @Override
	public cn.mxz.protocols.user.DogzP.DogzProOrBuilder getDogzOrBuilder() {
      return dogz_;
    }
    
    private void initFields() {
      dogz_ = cn.mxz.protocols.user.DogzP.DogzPro.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    @Override
	public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (hasDogz()) {
        if (!getDogz().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    @Override
	public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(10, dogz_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    @Override
	public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, dogz_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static cn.mxz.protocols.user.DogzP.DogzFighting parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static cn.mxz.protocols.user.DogzP.DogzFighting parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static cn.mxz.protocols.user.DogzP.DogzFighting parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static cn.mxz.protocols.user.DogzP.DogzFighting parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static cn.mxz.protocols.user.DogzP.DogzFighting parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static cn.mxz.protocols.user.DogzP.DogzFighting parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static cn.mxz.protocols.user.DogzP.DogzFighting parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static cn.mxz.protocols.user.DogzP.DogzFighting parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static cn.mxz.protocols.user.DogzP.DogzFighting parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static cn.mxz.protocols.user.DogzP.DogzFighting parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    @Override
	public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cn.mxz.protocols.user.DogzP.DogzFighting prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    @Override
	public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements cn.mxz.protocols.user.DogzP.DogzFightingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.mxz.protocols.user.DogzP.internal_static_cn_mxz_protocols_user_DogzFighting_descriptor;
      }
      
      @Override
	protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.mxz.protocols.user.DogzP.internal_static_cn_mxz_protocols_user_DogzFighting_fieldAccessorTable;
      }
      
      // Construct using cn.mxz.protocols.user.DogzP.DogzFighting.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDogzFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      @Override
	public Builder clear() {
        super.clear();
        if (dogzBuilder_ == null) {
          dogz_ = cn.mxz.protocols.user.DogzP.DogzPro.getDefaultInstance();
        } else {
          dogzBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      @Override
	public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      @Override
	public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.mxz.protocols.user.DogzP.DogzFighting.getDescriptor();
      }
      
      @Override
	public cn.mxz.protocols.user.DogzP.DogzFighting getDefaultInstanceForType() {
        return cn.mxz.protocols.user.DogzP.DogzFighting.getDefaultInstance();
      }
      
      @Override
	public cn.mxz.protocols.user.DogzP.DogzFighting build() {
        cn.mxz.protocols.user.DogzP.DogzFighting result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private cn.mxz.protocols.user.DogzP.DogzFighting buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        cn.mxz.protocols.user.DogzP.DogzFighting result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      @Override
	public cn.mxz.protocols.user.DogzP.DogzFighting buildPartial() {
        cn.mxz.protocols.user.DogzP.DogzFighting result = new cn.mxz.protocols.user.DogzP.DogzFighting(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (dogzBuilder_ == null) {
          result.dogz_ = dogz_;
        } else {
          result.dogz_ = dogzBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      @Override
	public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.mxz.protocols.user.DogzP.DogzFighting) {
          return mergeFrom((cn.mxz.protocols.user.DogzP.DogzFighting)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(cn.mxz.protocols.user.DogzP.DogzFighting other) {
        if (other == cn.mxz.protocols.user.DogzP.DogzFighting.getDefaultInstance()) return this;
        if (other.hasDogz()) {
          mergeDogz(other.getDogz());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      @Override
	public final boolean isInitialized() {
        if (hasDogz()) {
          if (!getDogz().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      @Override
	public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 82: {
              cn.mxz.protocols.user.DogzP.DogzPro.Builder subBuilder = cn.mxz.protocols.user.DogzP.DogzPro.newBuilder();
              if (hasDogz()) {
                subBuilder.mergeFrom(getDogz());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setDogz(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional .cn.mxz.protocols.user.DogzPro dogz = 10;
      private cn.mxz.protocols.user.DogzP.DogzPro dogz_ = cn.mxz.protocols.user.DogzP.DogzPro.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          cn.mxz.protocols.user.DogzP.DogzPro, cn.mxz.protocols.user.DogzP.DogzPro.Builder, cn.mxz.protocols.user.DogzP.DogzProOrBuilder> dogzBuilder_;
      @Override
	public boolean hasDogz() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      @Override
	public cn.mxz.protocols.user.DogzP.DogzPro getDogz() {
        if (dogzBuilder_ == null) {
          return dogz_;
        } else {
          return dogzBuilder_.getMessage();
        }
      }
      public Builder setDogz(cn.mxz.protocols.user.DogzP.DogzPro value) {
        if (dogzBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dogz_ = value;
          onChanged();
        } else {
          dogzBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setDogz(
          cn.mxz.protocols.user.DogzP.DogzPro.Builder builderForValue) {
        if (dogzBuilder_ == null) {
          dogz_ = builderForValue.build();
          onChanged();
        } else {
          dogzBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeDogz(cn.mxz.protocols.user.DogzP.DogzPro value) {
        if (dogzBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              dogz_ != cn.mxz.protocols.user.DogzP.DogzPro.getDefaultInstance()) {
            dogz_ =
              cn.mxz.protocols.user.DogzP.DogzPro.newBuilder(dogz_).mergeFrom(value).buildPartial();
          } else {
            dogz_ = value;
          }
          onChanged();
        } else {
          dogzBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearDogz() {
        if (dogzBuilder_ == null) {
          dogz_ = cn.mxz.protocols.user.DogzP.DogzPro.getDefaultInstance();
          onChanged();
        } else {
          dogzBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public cn.mxz.protocols.user.DogzP.DogzPro.Builder getDogzBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getDogzFieldBuilder().getBuilder();
      }
      @Override
	public cn.mxz.protocols.user.DogzP.DogzProOrBuilder getDogzOrBuilder() {
        if (dogzBuilder_ != null) {
          return dogzBuilder_.getMessageOrBuilder();
        } else {
          return dogz_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          cn.mxz.protocols.user.DogzP.DogzPro, cn.mxz.protocols.user.DogzP.DogzPro.Builder, cn.mxz.protocols.user.DogzP.DogzProOrBuilder> 
          getDogzFieldBuilder() {
        if (dogzBuilder_ == null) {
          dogzBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              cn.mxz.protocols.user.DogzP.DogzPro, cn.mxz.protocols.user.DogzP.DogzPro.Builder, cn.mxz.protocols.user.DogzP.DogzProOrBuilder>(
                  dogz_,
                  getParentForChildren(),
                  isClean());
          dogz_ = null;
        }
        return dogzBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:cn.mxz.protocols.user.DogzFighting)
    }
    
    static {
      defaultInstance = new DogzFighting(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:cn.mxz.protocols.user.DogzFighting)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_mxz_protocols_user_DogzListPro_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cn_mxz_protocols_user_DogzListPro_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_mxz_protocols_user_DogzPro_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cn_mxz_protocols_user_DogzPro_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_mxz_protocols_user_DogzSkillPro_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cn_mxz_protocols_user_DogzSkillPro_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_mxz_protocols_user_DogzFighting_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cn_mxz_protocols_user_DogzFighting_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\006dogz.p\022\025cn.mxz.protocols.user\032\nfractio" +
      "n.p\032\013attribute.p\"<\n\013DogzListPro\022-\n\005dogzs" +
      "\030( \003(\0132\036.cn.mxz.protocols.user.DogzPro\"\234" +
      "\002\n\007DogzPro\022\016\n\006typeId\030\n \002(\005\022\022\n\nisFighting" +
      "\030\025 \002(\010\022\r\n\005level\030\036 \002(\005\022\014\n\004step\0302 \002(\005\0222\n\006g" +
      "rowth\030< \002(\0132\".cn.mxz.protocols.user.Frac" +
      "tionPro\022\023\n\013isProtected\030= \002(\010\022\022\n\ndunWuTim" +
      "es\030Z \002(\005\022\021\n\tfishCount\030d \002(\005\022\026\n\016huiHunDan" +
      "Count\030n \002(\005\022\023\n\013protectProp\030x \002(\005\0223\n\005skil" +
      "l\030\202\001 \002(\0132#.cn.mxz.protocols.user.DogzSki",
      "llPro\"M\n\014DogzSkillPro\022\n\n\002id\030x \002(\005\022\026\n\rski" +
      "llAddition\030\214\001 \002(\005\022\031\n\020skillProbability\030\226\001" +
      " \002(\005\"<\n\014DogzFighting\022,\n\004dogz\030\n \001(\0132\036.cn." +
      "mxz.protocols.user.DogzPro"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        @Override
		public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_cn_mxz_protocols_user_DogzListPro_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_cn_mxz_protocols_user_DogzListPro_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_cn_mxz_protocols_user_DogzListPro_descriptor,
              new java.lang.String[] { "Dogzs", },
              cn.mxz.protocols.user.DogzP.DogzListPro.class,
              cn.mxz.protocols.user.DogzP.DogzListPro.Builder.class);
          internal_static_cn_mxz_protocols_user_DogzPro_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_cn_mxz_protocols_user_DogzPro_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_cn_mxz_protocols_user_DogzPro_descriptor,
              new java.lang.String[] { "TypeId", "IsFighting", "Level", "Step", "Growth", "IsProtected", "DunWuTimes", "FishCount", "HuiHunDanCount", "ProtectProp", "Skill", },
              cn.mxz.protocols.user.DogzP.DogzPro.class,
              cn.mxz.protocols.user.DogzP.DogzPro.Builder.class);
          internal_static_cn_mxz_protocols_user_DogzSkillPro_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_cn_mxz_protocols_user_DogzSkillPro_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_cn_mxz_protocols_user_DogzSkillPro_descriptor,
              new java.lang.String[] { "Id", "SkillAddition", "SkillProbability", },
              cn.mxz.protocols.user.DogzP.DogzSkillPro.class,
              cn.mxz.protocols.user.DogzP.DogzSkillPro.Builder.class);
          internal_static_cn_mxz_protocols_user_DogzFighting_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_cn_mxz_protocols_user_DogzFighting_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_cn_mxz_protocols_user_DogzFighting_descriptor,
              new java.lang.String[] { "Dogz", },
              cn.mxz.protocols.user.DogzP.DogzFighting.class,
              cn.mxz.protocols.user.DogzP.DogzFighting.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cn.mxz.protocols.user.FractionP.getDescriptor(),
          cn.mxz.protocols.user.AttributeP.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
