// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_shang_xiang.p

package cn.mxz.protocols.user;

public final class UserShangXiangP {
  private UserShangXiangP() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TodayIsGetProOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required bool noon = 10;
    boolean hasNoon();
    boolean getNoon();
    
    // required bool night = 11;
    boolean hasNight();
    boolean getNight();
    
    // required int32 countDown = 12;
    boolean hasCountDown();
    int getCountDown();
    
    // required bool hasReceiveNoon = 13;
    boolean hasHasReceiveNoon();
    boolean getHasReceiveNoon();
    
    // required bool hasReceiveNight = 14;
    boolean hasHasReceiveNight();
    boolean getHasReceiveNight();
    
    // required int32 hour = 15;
    boolean hasHour();
    int getHour();
  }
  public static final class TodayIsGetPro extends
      com.google.protobuf.GeneratedMessage
      implements TodayIsGetProOrBuilder {
    // Use TodayIsGetPro.newBuilder() to construct.
    private TodayIsGetPro(Builder builder) {
      super(builder);
    }
    private TodayIsGetPro(boolean noInit) {}
    
    private static final TodayIsGetPro defaultInstance;
    public static TodayIsGetPro getDefaultInstance() {
      return defaultInstance;
    }
    
    public TodayIsGetPro getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.mxz.protocols.user.UserShangXiangP.internal_static_cn_mxz_protocols_user_TodayIsGetPro_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.mxz.protocols.user.UserShangXiangP.internal_static_cn_mxz_protocols_user_TodayIsGetPro_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required bool noon = 10;
    public static final int NOON_FIELD_NUMBER = 10;
    private boolean noon_;
    public boolean hasNoon() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public boolean getNoon() {
      return noon_;
    }
    
    // required bool night = 11;
    public static final int NIGHT_FIELD_NUMBER = 11;
    private boolean night_;
    public boolean hasNight() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public boolean getNight() {
      return night_;
    }
    
    // required int32 countDown = 12;
    public static final int COUNTDOWN_FIELD_NUMBER = 12;
    private int countDown_;
    public boolean hasCountDown() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getCountDown() {
      return countDown_;
    }
    
    // required bool hasReceiveNoon = 13;
    public static final int HASRECEIVENOON_FIELD_NUMBER = 13;
    private boolean hasReceiveNoon_;
    public boolean hasHasReceiveNoon() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public boolean getHasReceiveNoon() {
      return hasReceiveNoon_;
    }
    
    // required bool hasReceiveNight = 14;
    public static final int HASRECEIVENIGHT_FIELD_NUMBER = 14;
    private boolean hasReceiveNight_;
    public boolean hasHasReceiveNight() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public boolean getHasReceiveNight() {
      return hasReceiveNight_;
    }
    
    // required int32 hour = 15;
    public static final int HOUR_FIELD_NUMBER = 15;
    private int hour_;
    public boolean hasHour() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public int getHour() {
      return hour_;
    }
    
    private void initFields() {
      noon_ = false;
      night_ = false;
      countDown_ = 0;
      hasReceiveNoon_ = false;
      hasReceiveNight_ = false;
      hour_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasNoon()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNight()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCountDown()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHasReceiveNoon()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHasReceiveNight()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHour()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(10, noon_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(11, night_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(12, countDown_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(13, hasReceiveNoon_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(14, hasReceiveNight_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(15, hour_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(10, noon_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(11, night_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(12, countDown_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(13, hasReceiveNoon_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(14, hasReceiveNight_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(15, hour_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static cn.mxz.protocols.user.UserShangXiangP.TodayIsGetPro parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static cn.mxz.protocols.user.UserShangXiangP.TodayIsGetPro parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static cn.mxz.protocols.user.UserShangXiangP.TodayIsGetPro parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static cn.mxz.protocols.user.UserShangXiangP.TodayIsGetPro parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static cn.mxz.protocols.user.UserShangXiangP.TodayIsGetPro parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static cn.mxz.protocols.user.UserShangXiangP.TodayIsGetPro parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static cn.mxz.protocols.user.UserShangXiangP.TodayIsGetPro parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static cn.mxz.protocols.user.UserShangXiangP.TodayIsGetPro parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static cn.mxz.protocols.user.UserShangXiangP.TodayIsGetPro parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static cn.mxz.protocols.user.UserShangXiangP.TodayIsGetPro parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cn.mxz.protocols.user.UserShangXiangP.TodayIsGetPro prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements cn.mxz.protocols.user.UserShangXiangP.TodayIsGetProOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.mxz.protocols.user.UserShangXiangP.internal_static_cn_mxz_protocols_user_TodayIsGetPro_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.mxz.protocols.user.UserShangXiangP.internal_static_cn_mxz_protocols_user_TodayIsGetPro_fieldAccessorTable;
      }
      
      // Construct using cn.mxz.protocols.user.UserShangXiangP.TodayIsGetPro.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        noon_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        night_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        countDown_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        hasReceiveNoon_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        hasReceiveNight_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        hour_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.mxz.protocols.user.UserShangXiangP.TodayIsGetPro.getDescriptor();
      }
      
      public cn.mxz.protocols.user.UserShangXiangP.TodayIsGetPro getDefaultInstanceForType() {
        return cn.mxz.protocols.user.UserShangXiangP.TodayIsGetPro.getDefaultInstance();
      }
      
      public cn.mxz.protocols.user.UserShangXiangP.TodayIsGetPro build() {
        cn.mxz.protocols.user.UserShangXiangP.TodayIsGetPro result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private cn.mxz.protocols.user.UserShangXiangP.TodayIsGetPro buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        cn.mxz.protocols.user.UserShangXiangP.TodayIsGetPro result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public cn.mxz.protocols.user.UserShangXiangP.TodayIsGetPro buildPartial() {
        cn.mxz.protocols.user.UserShangXiangP.TodayIsGetPro result = new cn.mxz.protocols.user.UserShangXiangP.TodayIsGetPro(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.noon_ = noon_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.night_ = night_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.countDown_ = countDown_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.hasReceiveNoon_ = hasReceiveNoon_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.hasReceiveNight_ = hasReceiveNight_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.hour_ = hour_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.mxz.protocols.user.UserShangXiangP.TodayIsGetPro) {
          return mergeFrom((cn.mxz.protocols.user.UserShangXiangP.TodayIsGetPro)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(cn.mxz.protocols.user.UserShangXiangP.TodayIsGetPro other) {
        if (other == cn.mxz.protocols.user.UserShangXiangP.TodayIsGetPro.getDefaultInstance()) return this;
        if (other.hasNoon()) {
          setNoon(other.getNoon());
        }
        if (other.hasNight()) {
          setNight(other.getNight());
        }
        if (other.hasCountDown()) {
          setCountDown(other.getCountDown());
        }
        if (other.hasHasReceiveNoon()) {
          setHasReceiveNoon(other.getHasReceiveNoon());
        }
        if (other.hasHasReceiveNight()) {
          setHasReceiveNight(other.getHasReceiveNight());
        }
        if (other.hasHour()) {
          setHour(other.getHour());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasNoon()) {
          
          return false;
        }
        if (!hasNight()) {
          
          return false;
        }
        if (!hasCountDown()) {
          
          return false;
        }
        if (!hasHasReceiveNoon()) {
          
          return false;
        }
        if (!hasHasReceiveNight()) {
          
          return false;
        }
        if (!hasHour()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 80: {
              bitField0_ |= 0x00000001;
              noon_ = input.readBool();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000002;
              night_ = input.readBool();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000004;
              countDown_ = input.readInt32();
              break;
            }
            case 104: {
              bitField0_ |= 0x00000008;
              hasReceiveNoon_ = input.readBool();
              break;
            }
            case 112: {
              bitField0_ |= 0x00000010;
              hasReceiveNight_ = input.readBool();
              break;
            }
            case 120: {
              bitField0_ |= 0x00000020;
              hour_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required bool noon = 10;
      private boolean noon_ ;
      public boolean hasNoon() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public boolean getNoon() {
        return noon_;
      }
      public Builder setNoon(boolean value) {
        bitField0_ |= 0x00000001;
        noon_ = value;
        onChanged();
        return this;
      }
      public Builder clearNoon() {
        bitField0_ = (bitField0_ & ~0x00000001);
        noon_ = false;
        onChanged();
        return this;
      }
      
      // required bool night = 11;
      private boolean night_ ;
      public boolean hasNight() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public boolean getNight() {
        return night_;
      }
      public Builder setNight(boolean value) {
        bitField0_ |= 0x00000002;
        night_ = value;
        onChanged();
        return this;
      }
      public Builder clearNight() {
        bitField0_ = (bitField0_ & ~0x00000002);
        night_ = false;
        onChanged();
        return this;
      }
      
      // required int32 countDown = 12;
      private int countDown_ ;
      public boolean hasCountDown() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getCountDown() {
        return countDown_;
      }
      public Builder setCountDown(int value) {
        bitField0_ |= 0x00000004;
        countDown_ = value;
        onChanged();
        return this;
      }
      public Builder clearCountDown() {
        bitField0_ = (bitField0_ & ~0x00000004);
        countDown_ = 0;
        onChanged();
        return this;
      }
      
      // required bool hasReceiveNoon = 13;
      private boolean hasReceiveNoon_ ;
      public boolean hasHasReceiveNoon() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public boolean getHasReceiveNoon() {
        return hasReceiveNoon_;
      }
      public Builder setHasReceiveNoon(boolean value) {
        bitField0_ |= 0x00000008;
        hasReceiveNoon_ = value;
        onChanged();
        return this;
      }
      public Builder clearHasReceiveNoon() {
        bitField0_ = (bitField0_ & ~0x00000008);
        hasReceiveNoon_ = false;
        onChanged();
        return this;
      }
      
      // required bool hasReceiveNight = 14;
      private boolean hasReceiveNight_ ;
      public boolean hasHasReceiveNight() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public boolean getHasReceiveNight() {
        return hasReceiveNight_;
      }
      public Builder setHasReceiveNight(boolean value) {
        bitField0_ |= 0x00000010;
        hasReceiveNight_ = value;
        onChanged();
        return this;
      }
      public Builder clearHasReceiveNight() {
        bitField0_ = (bitField0_ & ~0x00000010);
        hasReceiveNight_ = false;
        onChanged();
        return this;
      }
      
      // required int32 hour = 15;
      private int hour_ ;
      public boolean hasHour() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public int getHour() {
        return hour_;
      }
      public Builder setHour(int value) {
        bitField0_ |= 0x00000020;
        hour_ = value;
        onChanged();
        return this;
      }
      public Builder clearHour() {
        bitField0_ = (bitField0_ & ~0x00000020);
        hour_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:cn.mxz.protocols.user.TodayIsGetPro)
    }
    
    static {
      defaultInstance = new TodayIsGetPro(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:cn.mxz.protocols.user.TodayIsGetPro)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_mxz_protocols_user_TodayIsGetPro_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cn_mxz_protocols_user_TodayIsGetPro_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022user_shang_xiang.p\022\025cn.mxz.protocols.u" +
      "ser\"~\n\rTodayIsGetPro\022\014\n\004noon\030\n \002(\010\022\r\n\005ni" +
      "ght\030\013 \002(\010\022\021\n\tcountDown\030\014 \002(\005\022\026\n\016hasRecei" +
      "veNoon\030\r \002(\010\022\027\n\017hasReceiveNight\030\016 \002(\010\022\014\n" +
      "\004hour\030\017 \002(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_cn_mxz_protocols_user_TodayIsGetPro_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_cn_mxz_protocols_user_TodayIsGetPro_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_cn_mxz_protocols_user_TodayIsGetPro_descriptor,
              new java.lang.String[] { "Noon", "Night", "CountDown", "HasReceiveNoon", "HasReceiveNight", "Hour", },
              cn.mxz.protocols.user.UserShangXiangP.TodayIsGetPro.class,
              cn.mxz.protocols.user.UserShangXiangP.TodayIsGetPro.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
