package cn.mxz.loganalysis;

import java.util.Set;

import com.google.common.collect.Sets;



/**
 * Hello world!
 *
 */
public class App2 
{
    public static void main( String[] args )
    {
    	
    	
//    	1、玩家当前的等级
//    	2、玩家当前引导的位置
//    	3、玩家当前的在线时长（这个暂时我想办法让对方提供）
//    	4、玩家的登录次数
//    	5、昨日注册今日是否登录
//    	new GuideAnalysis().start();//引导节点分析
//    	new LoginAnalysis().start();//登陆日志分析
//    	new ServiceAnalysis().start();
//    	new ConsumeAnalysis().start();//产出日志
//    	new ConsumeAnalysis2().start();// 这个是新版最详尽的 产出日志
//    	new TaskAnalysis().start(); //成就任务达成 分析  哪些任务 玩家完成了
//    	new LevelAnalysis().start();//等级分布情况
    	//某日创建的人
//    	Set<String> users = new CreateUserCount().getUsers("2014-08-13");
//    	Set<String> users14Login = new LoginUserCount().getUsers("2014-08-14");
//    	users14Login.removeAll(users);
//    	
//    	System.out.println("次日留存:" + (users14Login.size() + 0f) / users.size());
//    	for (String string : users) {
//			System.out.println(string);
//		}
//		System.out.println(users);
//    	System.out.println(new CreateUserCount().getUsers("2014-08-14").size());
//    	Set<String> users2 = new LoginUserCount().getUsers("2014-08-14");
//    	for (String string : users2) {
//			System.out.println(string);
//		}
//		System.out.println(users2);
    	
    	
    	Set<String> createOn13 = Sets.newHashSet();	
		createOn13.add("→_→");
    	createOn13.add("babby");
    	createOn13.add("");
    	createOn13.add("llsny");
    	createOn13.add("LoLWC");
    	createOn13.add("Mr汉尼拔");
    	createOn13.add("STG丶i");
    	createOn13.add("wxggs");
    	createOn13.add("阿伏干秀乐");
    	createOn13.add("阿仑歪惜");
    	createOn13.add("阿史那奏沁");
    	createOn13.add("阿水");
    	createOn13.add("阿思没鞭涵");
    	createOn13.add("阿勿嘀融苓");
    	createOn13.add("阿西");
    	createOn13.add("啊黑");
    	createOn13.add("安迟淇藻");
    	createOn13.add("安都眇瓯");
    	createOn13.add("安国巾靖");
    	createOn13.add("安金绿泌");
    	createOn13.add("安金幽姑");
    	createOn13.add("安陵夙莎");
    	createOn13.add("安期岁嘏");
    	createOn13.add("安阳浪滢");
    	createOn13.add("犴茧姳");
    	createOn13.add("按暄妍");
    	createOn13.add("暗殇");
    	createOn13.add("昂儿音");
    	createOn13.add("昂记询");
    	createOn13.add("敖材蕾");
    	createOn13.add("奥敦韧经");
    	createOn13.add("奥鲁幻璨");
    	createOn13.add("巴公基虚");
    	createOn13.add("芭谷妆");
    	createOn13.add("芭拳化");
    	createOn13.add("拔拔衔欢");
    	createOn13.add("拔列兰裳芑");
    	createOn13.add("拔列兰窕柳");
    	createOn13.add("拔略传如");
    	createOn13.add("跋谆瑾");
    	createOn13.add("把镫侨");
    	createOn13.add("把利袋漓");
    	createOn13.add("爸爸");
    	createOn13.add("罢敌蒂苞");
    	createOn13.add("罢敌卯络");
    	createOn13.add("罢涕骏");
    	createOn13.add("白冥亿友");
    	createOn13.add("白冥悠棱");
    	createOn13.add("白亚综蔓");
    	createOn13.add("白杨提判姳");
    	createOn13.add("白杨提屏飘");
    	createOn13.add("白乙");
    	createOn13.add("百鬼夜行");
    	createOn13.add("百鬼夜游");
    	createOn13.add("百岁樱");
    	createOn13.add("百同楚");
    	createOn13.add("般厚栽");
    	createOn13.add("苞丘苕薇");
    	createOn13.add("薄冰");
    	createOn13.add("薄姑在黧");
    	createOn13.add("饱架佾");
    	createOn13.add("保勿侣");
    	createOn13.add("鲍丘邈里");
    	createOn13.add("鲍俎乂宵");
    	createOn13.add("悲哀小熊熊");
    	createOn13.add("悲坪皤");
    	createOn13.add("北郭导潜");
    	createOn13.add("北践冷");
    	createOn13.add("北木南烟");
    	createOn13.add("北殷传萍");
    	createOn13.add("孛术鲁拘艺");
    	createOn13.add("背摩缓");
    	createOn13.add("倍俟赡芙");
    	createOn13.add("蹦卖茹");
    	createOn13.add("逼整红");
    	createOn13.add("彼焰绍");
    	createOn13.add("闭珊织砥");
    	createOn13.add("邲娇怜");
    	createOn13.add("陛下");
    	createOn13.add("璧岁浠");
    	createOn13.add("边朗郗");
    	createOn13.add("彪课漫");
    	createOn13.add("邠欻苹");
    	createOn13.add("邠远夜");
    	createOn13.add("宾牟肪婷");
    	createOn13.add("斌乃南");
    	createOn13.add("冰武者");
    	createOn13.add("邴亘璎");
    	createOn13.add("邴望妱");
    	createOn13.add("炳获嫦");
    	createOn13.add("并官钒沉");
    	createOn13.add("并官岚圭");
    	createOn13.add("伯比锻骥");
    	createOn13.add("伯常身娇");
    	createOn13.add("伯常谕瑶");
    	createOn13.add("伯有玠渝");
    	createOn13.add("伯有爪嫦");
    	createOn13.add("驳马折潮");
    	createOn13.add("帛钊努");
    	createOn13.add("亳刺眰");
    	createOn13.add("僰蚀勤");
    	createOn13.add("卜绰梅");
    	createOn13.add("步大汗册萤");
    	createOn13.add("步叔柬昱");
    	createOn13.add("惨淡...");
    	createOn13.add("苍穹");
    	createOn13.add("曾经的回忆");
    	createOn13.add("曾琅湄");
    	createOn13.add("昌遛萩");
    	createOn13.add("常焰镅");
    	createOn13.add("超哥战江湖");
    	createOn13.add("车牲薰");
    	createOn13.add("臣运佳");
    	createOn13.add("尘世");
    	createOn13.add("成洒弓");
    	createOn13.add("迟睛珺");
    	createOn13.add("仇超徽");
    	createOn13.add("出妻妮");
    	createOn13.add("楚穹溪");
    	createOn13.add("春笙妖");
    	createOn13.add("淳于蝉梦");
    	createOn13.add("淳于敛浓");
    	createOn13.add("琮献奚");
    	createOn13.add("大白牙");
    	createOn13.add("大大");
    	createOn13.add("大大泡泡糖");
    	createOn13.add("大头狂神");
    	createOn13.add("大轸婉");
    	createOn13.add("澹台缮妙");
    	createOn13.add("刀砚芑");
    	createOn13.add("得我哭泣");
    	createOn13.add("邓夫滢");
    	createOn13.add("第二屋泸");
    	createOn13.add("第七典蝶");
    	createOn13.add("第七键苓");
    	createOn13.add("第七览萤");
    	createOn13.add("第三贴荧");
    	createOn13.add("第四煜懋");
    	createOn13.add("第一樱伶");
    	createOn13.add("刁侃轲");
    	createOn13.add("东方徂梅");
    	createOn13.add("东郭侗莘");
    	createOn13.add("东皇昊天");
    	createOn13.add("东门馔樾");
    	createOn13.add("窦精赀");
    	createOn13.add("独孤佛旻");
    	createOn13.add("端黛轸");
    	createOn13.add("多情灰太狼");
    	createOn13.add("哆哆哆哆");
    	createOn13.add("范町鸢");
    	createOn13.add("房灿曼");
    	createOn13.add("肥先生");
    	createOn13.add("费蕊冷");
    	createOn13.add("鼢冒蓬颉");
    	createOn13.add("粉魔丶");
    	createOn13.add("风妣皕");
    	createOn13.add("扶鸣仑");
    	createOn13.add("付镪苕");
    	createOn13.add("傅其察姬");
    	createOn13.add("富察饬荃");
    	createOn13.add("干攻侨");
    	createOn13.add("刚伉践");
    	createOn13.add("刚浈仙");
    	createOn13.add("高阳琼郗");
    	createOn13.add("哥舒彩琼");
    	createOn13.add("公孙侨蓄");
    	createOn13.add("公羊附豫");
    	createOn13.add("公冶煜亭");
    	createOn13.add("谷粱藤星");
    	createOn13.add("寡人");
    	createOn13.add("寡人。");
    	createOn13.add("何为");
    	createOn13.add("赫连礼休");
    	createOn13.add("赫舍里锹娅");
    	createOn13.add("红月");
    	createOn13.add("洪球草");
    	createOn13.add("后会有期");
    	createOn13.add("虎抽七");
    	createOn13.add("花季、王朝");
    	createOn13.add("华璎妙");
    	createOn13.add("皇甫灿呤");
    	createOn13.add("皇甫软钗");
    	createOn13.add("翚精唯");
    	createOn13.add("惠宅昔");
    	createOn13.add("魂");
    	createOn13.add("火舞邪狂");
    	createOn13.add("纪妩唯");
    	createOn13.add("纪训士");
    	createOn13.add("济粽娘");
    	createOn13.add("冀浈排");
    	createOn13.add("贾羿珹");
    	createOn13.add("见见哥");
    	createOn13.add("建士思");
    	createOn13.add("江进轻");
    	createOn13.add("江屏萌");
    	createOn13.add("姜佳勇");
    	createOn13.add("晋奎盈");
    	createOn13.add("荆鹊深");
    	createOn13.add("景败师");
    	createOn13.add("景蹇瑶");
    	createOn13.add("九吾悍沾");
    	createOn13.add("鞠款轲");
    	createOn13.add("鞠铨羚");
    	createOn13.add("剧袋莘");
    	createOn13.add("隽属瑗");
    	createOn13.add("卡特琳娜");
    	createOn13.add("开值诗");
    	createOn13.add("柯粥函");
    	createOn13.add("空桑心心");
    	createOn13.add("空同鲸南");
    	createOn13.add("空同霄霞");
    	createOn13.add("空桐谤屺");
    	createOn13.add("空相魁佟");
    	createOn13.add("旷烷璐");
    	createOn13.add("昆虢幽");
    	createOn13.add("昆飏绰");
    	createOn13.add("垃圾");
    	createOn13.add("蓝闹当");
    	createOn13.add("乐正薇鹤");
    	createOn13.add("冷血飞冰");
    	createOn13.add("黎肩莎");
    	createOn13.add("李戒璇");
    	createOn13.add("力牛");
    	createOn13.add("利睑昔");
    	createOn13.add("郦樽俪");
    	createOn13.add("联盟老五");
    	createOn13.add("廉洁素");
    	createOn13.add("练情宕");
    	createOn13.add("泠裹咏");
    	createOn13.add("凌媛甜");
    	createOn13.add("龙赴旋");
    	createOn13.add("蝼蚁");
    	createOn13.add("卢絺姐");
    	createOn13.add("卢处嘏");
    	createOn13.add("卢来丹");
    	createOn13.add("鲁巴是只狗");
    	createOn13.add("路者风");
    	createOn13.add("罗刹丶");
    	createOn13.add("吕意寓");
    	createOn13.add("吕友恒");
    	createOn13.add("马味莺");
    	createOn13.add("茆弟珠");
    	createOn13.add("貌似");
    	createOn13.add("么么哒");
    	createOn13.add("没路真舌雅");
    	createOn13.add("枚责香");
    	createOn13.add("美男子");
    	createOn13.add("美女");
    	createOn13.add("门句滢");
    	createOn13.add("蒙面战神");
    	createOn13.add("蒙顺泰");
    	createOn13.add("蒙韬鄢");
    	createOn13.add("密赛呤");
    	createOn13.add("明内舒");
    	createOn13.add("莫丶小鬼");
    	createOn13.add("莫离");
    	createOn13.add("莫问");
    	createOn13.add("莫问、");
    	createOn13.add("牟敛冰");
    	createOn13.add("幕诗茵");
    	createOn13.add("慕容钜瓴");
    	createOn13.add("慕容幼贻");
    	createOn13.add("穆埋芜");
    	createOn13.add("穆制茕");
    	createOn13.add("那拉断闵");
    	createOn13.add("那拉彦樟");
    	createOn13.add("纳喇裹弋");
    	createOn13.add("迺坟淼");
    	createOn13.add("南宫驾日");
    	createOn13.add("南宫锏镜");
    	createOn13.add("南宫困叆");
    	createOn13.add("南宫详苹");
    	createOn13.add("倪娣萱");
    	createOn13.add("你妹的");
    	createOn13.add("念徨宾");
    	createOn13.add("牛仔裤");
    	createOn13.add("钮甚徽");
    	createOn13.add("欧阳雀道");
    	createOn13.add("潘钗颀");
    	createOn13.add("泮棣汶");
    	createOn13.add("胖帅");
    	createOn13.add("裴迈妶");
    	createOn13.add("彭蒂奇");
    	createOn13.add("辟闾銮恢");
    	createOn13.add("破落那绪逸");
    	createOn13.add("普料蓝");
    	createOn13.add("普六茹君潍");
    	createOn13.add("普命莉");
    	createOn13.add("亓俱遨");
    	createOn13.add("祁些乃");
    	createOn13.add("其乐无穷");
    	createOn13.add("麒泰羽");
    	createOn13.add("启迪");
    	createOn13.add("弃天帝");
    	createOn13.add("千羽怜寒");
    	createOn13.add("千羽沐阳");
    	createOn13.add("戗憬煇灲");
    	createOn13.add("桥镰岢");
    	createOn13.add("且觊娉");
    	createOn13.add("琴楠嫣");
    	createOn13.add("琴舍活");
    	createOn13.add("青放遇");
    	createOn13.add("青郡珠");
    	createOn13.add("青鸾");
    	createOn13.add("倾城南诗╮");
    	createOn13.add("秋婷");
    	createOn13.add("区培蕊");
    	createOn13.add("诎复奴");
    	createOn13.add("诎渔舸");
    	createOn13.add("曲晤尼");
    	createOn13.add("曲倚瓴");
    	createOn13.add("去你丫的");
    	createOn13.add("权各苹");
    	createOn13.add("饶赔雅");
    	createOn13.add("任靠柯");
    	createOn13.add("任忘茁");
    	createOn13.add("阮钗玟");
    	createOn13.add("阮岂奕");
    	createOn13.add("涩少年");
    	createOn13.add("杀猪刀");
    	createOn13.add("上官算娃");
    	createOn13.add("申屠道阳");
    	createOn13.add("莘庭芯");
    	createOn13.add("神♚皇");
    	createOn13.add("神棍骗天下");
    	createOn13.add("神农沧嵝");
    	createOn13.add("神农决众");
    	createOn13.add("神农派逦");
    	createOn13.add("神奇少年");
    	createOn13.add("沈霆姚");
    	createOn13.add("审绪赀");
    	createOn13.add("十七哥");
    	createOn13.add("时阁芬");
    	createOn13.add("世零一");
    	createOn13.add("弑神ジ修罗");
    	createOn13.add("噬魂戰天");
    	createOn13.add("殳睑皕");
    	createOn13.add("叔敖婵佩");
    	createOn13.add("帅得想上吊");
    	createOn13.add("双子");
    	createOn13.add("水雀月");
    	createOn13.add("水天神瀛");
    	createOn13.add("司空喜歆");
    	createOn13.add("司空遵侨");
    	createOn13.add("司徒甯莺");
    	createOn13.add("司徒菀艳");
    	createOn13.add("宋胜侠");
    	createOn13.add("宋朽晴");
    	createOn13.add("素黎睦少");
    	createOn13.add("粟同璐");
    	createOn13.add("随风");
    	createOn13.add("孙始欣");
    	createOn13.add("台銮赞");
    	createOn13.add("太叔坟楠");
    	createOn13.add("谈婵莉");
    	createOn13.add("覃天");
    	createOn13.add("谭渝眧");
    	createOn13.add("汤姆猫");
    	createOn13.add("涛涛");
    	createOn13.add("滕胃昭");
    	createOn13.add("天");
    	createOn13.add("天才大叔");
    	createOn13.add("天莫邪");
    	createOn13.add("天天微乐");
    	createOn13.add("彤彤");
    	createOn13.add("秃发侧珊");
    	createOn13.add("兔慨苏");
    	createOn13.add("拓拔搅琬");
    	createOn13.add("外婆的点心");
    	createOn13.add("万俟铮轻");
    	createOn13.add("王灵裴");
    	createOn13.add("威少");
    	createOn13.add("韦锻柔");
    	createOn13.add("唯美爱情");
    	createOn13.add("维也纳の火");
    	createOn13.add("委跃慕");
    	createOn13.add("卫螗瓶");
    	createOn13.add("温柔南诗﹋");
    	createOn13.add("乌鸦");
    	createOn13.add("巫马循穆");
    	createOn13.add("无题");
    	createOn13.add("吴君音");
    	createOn13.add("西郭羸霏");
    	createOn13.add("袭天");
    	createOn13.add("夏侯慈皕");
    	createOn13.add("夏侯驯舜");
    	createOn13.add("先生的书童");
    	createOn13.add("鲜于榭涧");
    	createOn13.add("线葫风");
    	createOn13.add("潇潇雅韵");
    	createOn13.add("小飞猪");
    	createOn13.add("小苹果");
    	createOn13.add("小五灬");
    	createOn13.add("小星星");
    	createOn13.add("小铱");
    	createOn13.add("小贼猫");
    	createOn13.add("邪情丶傲");
    	createOn13.add("鈊葬灬宝贝");
    	createOn13.add("鈊葬灬龙哥");
    	createOn13.add("鈊葬灬小龙");
    	createOn13.add("新月");
    	createOn13.add("熊煜瀣");
    	createOn13.add("修镀锐");
    	createOn13.add("轩轩");
    	createOn13.add("轩辕绥纯");
    	createOn13.add("轩辕云天");
    	createOn13.add("玄殿壬");
    	createOn13.add("薛睦滨");
    	createOn13.add("雪后阳光");
    	createOn13.add("雪后阳光1");
    	createOn13.add("雪花谣");
    	createOn13.add("牙牙");
    	createOn13.add("闫宥非");
    	createOn13.add("颜城穗");
    	createOn13.add("燕璨瑚");
    	createOn13.add("燕沅妒");
    	createOn13.add("阳竞芙");
    	createOn13.add("卬工书");
    	createOn13.add("妖怪是我");
    	createOn13.add("爷爷");
    	createOn13.add("叶血芊");
    	createOn13.add("伊利早餐奶");
    	createOn13.add("移炊滔");
    	createOn13.add("移婚暖");
    	createOn13.add("移弩雯");
    	createOn13.add("移晔岚");
    	createOn13.add("忆梦灬溪");
    	createOn13.add("易杖矫");
    	createOn13.add("阴笼夕");
    	createOn13.add("殷七跃");
    	createOn13.add("尹周燕");
    	createOn13.add("婴枫嫔");
    	createOn13.add("嬴窑唯");
    	createOn13.add("雍旋夕");
    	createOn13.add("永恒");
    	createOn13.add("忧伤&调调");
    	createOn13.add("由听壮");
    	createOn13.add("游戏而已丶");
    	createOn13.add("有霁沙");
    	createOn13.add("右辽幽");
    	createOn13.add("鱼侣姥");
    	createOn13.add("宇粹模");
    	createOn13.add("郁迈萌");
    	createOn13.add("喻拍菱");
    	createOn13.add("喻邑奕");
    	createOn13.add("元始天尊");
    	createOn13.add("员沁葵");
    	createOn13.add("员稔珮");
    	createOn13.add("袁寿瑰");
    	createOn13.add("岳眷苹");
    	createOn13.add("悦风");
    	createOn13.add("云绝笑");
    	createOn13.add("臧径渝");
    	createOn13.add("翟底瓦");
    	createOn13.add("粘对学");
    	createOn13.add("瞻粲娓");
    	createOn13.add("战天下");
    	createOn13.add("湛婵雨");
    	createOn13.add("张磨茫");
    	createOn13.add("彰拙书");
    	createOn13.add("长孙奏茜");
    	createOn13.add("掌杰瑶");
    	createOn13.add("赵薰恩");
    	createOn13.add("真筌珑");
    	createOn13.add("甄鹄荪");
    	createOn13.add("征冽阳");
    	createOn13.add("政洁妍yu");
    	createOn13.add("直婚绣");
    	createOn13.add("治谋彗");
    	createOn13.add("治鼠慈");
    	createOn13.add("掷眠皕");
    	createOn13.add("智恺天");
    	createOn13.add("终性升");
    	createOn13.add("钟舍罡");
    	createOn13.add("钟私莺");
    	createOn13.add("衷虔颁");
    	createOn13.add("诸葛旭昼");
    	createOn13.add("诸烬阜");
    	createOn13.add("子车盐僮");
    	createOn13.add("紫嚣雉");
    	createOn13.add("訾面愫");
    	createOn13.add("宗鳜娅");
    	createOn13.add("纵琨淹");
    	createOn13.add("邹换函");
    	createOn13.add("驺笺乐");
    	createOn13.add("醉红尘");
    	createOn13.add("左斡奴");
    	createOn13.add("作死星人");
    	
    	new LoginUserCount().getUsers(createOn13, "2014-08-14");
//    	
//    	
//    	
//    	Set<String> set2 = Sets.newHashSet();
//    	
//		set2.add("→_→");
//    	set2.add("");
//    	set2.add("babby");
//    	set2.add("llsny");
//    	set2.add("LoLWC");
//    	set2.add("Mr");
//    	set2.add("wxggs");
//    	set2.add("阿勒根当旁");
//    	set2.add("阿勒根末立");
//    	set2.add("阿仑耻赞");
//    	set2.add("阿热晦莘");
//    	set2.add("阿史那奏沁");
//    	set2.add("阿水");
//    	set2.add("啊黑");
//    	set2.add("安迟淇藻");
//    	set2.add("安都眇瓯");
//    	set2.add("安国颔希");
//    	set2.add("安国巾靖");
//    	set2.add("安国沅虞");
//    	set2.add("安金绿泌");
//    	set2.add("安薰妩");
//    	set2.add("安阳炽飘");
//    	set2.add("按暄妍");
//    	set2.add("暗殇");
//    	set2.add("昂记询");
//    	set2.add("昂隙媚");
//    	set2.add("敖材蕾");
//    	set2.add("敖敢嫩");
//    	set2.add("奥八马丶");
//    	set2.add("奥鲁幻璨");
//    	set2.add("奥屯总侃");
//    	set2.add("巴食东");
//    	set2.add("芭谷妆");
//    	set2.add("拔也鹄丞");
//    	set2.add("把利赞颐");
//    	set2.add("把豌墨");
//    	set2.add("爸爸");
//    	set2.add("罢涕骏");
//    	set2.add("白冥亿友");
//    	set2.add("白冥悠棱");
//    	set2.add("白亚综蔓");
//    	set2.add("白杨提屏飘");
//    	set2.add("百鬼夜游");
//    	set2.add("柏侯映澧");
//    	set2.add("褒抛锱");
//    	set2.add("薄冰");
//    	set2.add("薄姑在黧");
//    	set2.add("薄姑芝絮");
//    	set2.add("薄野循什");
//    	set2.add("抱着树袋熊");
//    	set2.add("豹硕针");
//    	set2.add("悲哀小熊熊");
//    	set2.add("悲测稍");
//    	set2.add("北枫晖");
//    	set2.add("孛术鲁拘艺");
//    	set2.add("贲训蓝");
//    	set2.add("逼玩姳");
//    	set2.add("苾旋佼");
//    	set2.add("陛下");
//    	set2.add("敝润柱");
//    	set2.add("璧袍亲");
//    	set2.add("璧岁浠");
//    	set2.add("斌案宏");
//    	set2.add("斌乃南");
//    	set2.add("冰武者");
//    	set2.add("邴亘璎");
//    	set2.add("秉局裴");
//    	set2.add("炳获嫦");
//    	set2.add("剥铎采");
//    	set2.add("伯比锻骥");
//    	set2.add("伯德醒镔");
//    	set2.add("伯丰仆莲");
//    	set2.add("伯封锋浙");
//    	set2.add("帛钊努");
//    	set2.add("布叔满诲晴");
//    	set2.add("步大汗册萤");
//    	set2.add("步叔柬昱");
//    	set2.add("裁决者");
//    	set2.add("曾经的回忆");
//    	set2.add("超人星尊");
//    	set2.add("迟睛珺");
//    	set2.add("赤脚的猫");
//    	set2.add("仇赣值");
//    	set2.add("出妻妮");
//    	set2.add("楚穹溪");
//    	set2.add("淳于蝉梦");
//    	set2.add("琮献奚");
//    	set2.add("脆弱的后排");
//    	set2.add("大白牙");
//    	set2.add("大大泡泡糖");
//    	set2.add("大风车");
//    	set2.add("大林");
//    	set2.add("单楣湘");
//    	set2.add("淡漠");
//    	set2.add("党夜荷");
//    	set2.add("刀砚芑");
//    	set2.add("邓夫滢");
//    	set2.add("第八光");
//    	set2.add("第六欢湮");
//    	set2.add("第七典蝶");
//    	set2.add("第四煜懋");
//    	set2.add("第五丶倾城");
//    	set2.add("第一樱伶");
//    	set2.add("东方古妙");
//    	set2.add("东郭侗莘");
//    	set2.add("东郭贞月");
//    	set2.add("东皇昊天");
//    	set2.add("独");
//    	set2.add("独怵");
//    	set2.add("独孤佛旻");
//    	set2.add("独恋天秤");
//    	set2.add("端黛轸");
//    	set2.add("多情灰太狼");
//    	set2.add("多筌塬");
//    	set2.add("哆哆哆哆");
//    	set2.add("法神小铱");
//    	set2.add("法瓦心");
//    	set2.add("范町鸢");
//    	set2.add("非白即墨");
//    	set2.add("飝鷥龘");
//    	set2.add("符葵子");
//    	set2.add("府城冰少");
//    	set2.add("干从坚");
//    	set2.add("刚伉践");
//    	set2.add("刚浈仙");
//    	set2.add("哥舒彩琼");
//    	set2.add("公羊突骔");
//    	set2.add("归海卷隅");
//    	set2.add("鬼象苏");
//    	set2.add("何为");
//    	set2.add("赫遗绫");
//    	set2.add("红月");
//    	set2.add("洪球草");
//    	set2.add("后会有期");
//    	set2.add("虎锡宵");
//    	set2.add("花季、王朝");
//    	set2.add("华璎妙");
//    	set2.add("华仔");
//    	set2.add("宦锯湄");
//    	set2.add("黄氏卐家族");
//    	set2.add("会飞的牛子");
//    	set2.add("惠宅昔");
//    	set2.add("混乱天堂");
//    	set2.add("魂");
//    	set2.add("火拔芸澔");
//    	set2.add("叽哩咕鲁");
//    	set2.add("鸡町济");
//    	set2.add("籍动湃");
//    	set2.add("纪妩唯");
//    	set2.add("季末花依旧");
//    	set2.add("季孙络萌");
//    	set2.add("贾羿珹");
//    	set2.add("捡来的");
//    	set2.add("见见哥");
//    	set2.add("剑圣");
//    	set2.add("尐潴児");
//    	set2.add("金火颀");
//    	set2.add("荆庭娜");
//    	set2.add("景蹇瑶");
//    	set2.add("景私诚");
//    	set2.add("救攻苞");
//    	set2.add("就是不吃药");
//    	set2.add("康改逦");
//    	set2.add("空桑摘珮");
//    	set2.add("空同霄霞");
//    	set2.add("空桐谤屺");
//    	set2.add("旷稚春");
//    	set2.add("昆势翻");
//    	set2.add("昆飏绰");
//    	set2.add("兰博基尼");
//    	set2.add("蓝给索");
//    	set2.add("劳同曦");
//    	set2.add("老衲来洗头");
//    	set2.add("乐正薇鹤");
//    	set2.add("李戒璇");
//    	set2.add("联盟老五");
//    	set2.add("练情宕");
//    	set2.add("临沂小伙");
//    	set2.add("灵歌");
//    	set2.add("泠裹咏");
//    	set2.add("刘铭");
//    	set2.add("龙魂");
//    	set2.add("龍龖龘");
//    	set2.add("楼件寓");
//    	set2.add("蝼蚁");
//    	set2.add("卢絺姐");
//    	set2.add("鲁巴是只狗");
//    	set2.add("陆尘");
//    	set2.add("鹿算丕");
//    	set2.add("罗速剌");
//    	set2.add("罗兄凌");
//    	set2.add("落九天");
//    	set2.add("吕友恒");
//    	set2.add("马罡啸");
//    	set2.add("马味莺");
//    	set2.add("买篮爱");
//    	set2.add("茅侦砉");
//    	set2.add("貌似");
//    	set2.add("么么哒");
//    	set2.add("美女");
//    	set2.add("蒙顺泰");
//    	set2.add("糜句羡");
//    	set2.add("瞄人缝");
//    	set2.add("莫离");
//    	set2.add("莫问");
//    	set2.add("默默守望");
//    	set2.add("牟敛冰");
//    	set2.add("慕容幼贻");
//    	set2.add("纳兰弹奕");
//    	set2.add("迺坟淼");
//    	set2.add("南宫详苹");
//    	set2.add("能吃了你啊");
//    	set2.add("你妹的");
//    	set2.add("念徨宾");
//    	set2.add("潘钗颀");
//    	set2.add("胖哥");
//    	set2.add("胖帅");
//    	set2.add("裴迈妶");
//    	set2.add("普料蓝");
//    	set2.add("普命莉");
//    	set2.add("妻管严");
//    	set2.add("漆尖湮");
//    	set2.add("亓俱遨");
//    	set2.add("麒悉斐");
//    	set2.add("弃天帝");
//    	set2.add("千与千寻");
//    	set2.add("牵手女神i");
//    	set2.add("强忱苕");
//    	set2.add("巧克力");
//    	set2.add("琴产姥");
//    	set2.add("轻笑丶倾城");
//    	set2.add("倾城南诗╮");
//    	set2.add("邱秃纹");
//    	set2.add("裘守举");
//    	set2.add("区培蕊");
//    	set2.add("曲倚瓴");
//    	set2.add("圈圈很圆");
//    	set2.add("权各苹");
//    	set2.add("泉钰曜");
//    	set2.add("任靠柯");
//    	set2.add("任忘茁");
//    	set2.add("荣昨蝉");
//    	set2.add("阮钗玟");
//    	set2.add("阮岂奕");
//    	set2.add("韶愁荷");
//    	set2.add("邵女妱");
//    	set2.add("神、瑶瑶");
//    	set2.add("神♚皇");
//    	set2.add("神棍在此");
//    	set2.add("神农决众");
//    	set2.add("神农派逦");
//    	set2.add("神奇少年");
//    	set2.add("沈霆姚");
//    	set2.add("审绪赀");
//    	set2.add("十七哥");
//    	set2.add("石狮");
//    	set2.add("世琨廿");
//    	set2.add("世零一");
//    	set2.add("是采淝");
//    	set2.add("弑神ジ修罗");
//    	set2.add("殳睑皕");
//    	set2.add("叔敖婵佩");
//    	set2.add("帅得想上吊");
//    	set2.add("司空遵侨");
//    	set2.add("司马弟玟");
//    	set2.add("司马宏哨");
//    	set2.add("司徒、芸儿");
//    	set2.add("司徒菀艳");
//    	set2.add("素黎矮炼");
//    	set2.add("太史贯萧");
//    	set2.add("覃天");
//    	set2.add("汤姆猫");
//    	set2.add("涛涛");
//    	set2.add("天");
//    	set2.add("天才大叔");
//    	set2.add("通天教主");
//    	set2.add("佟魂紫");
//    	set2.add("佟亦轨");
//    	set2.add("彤彤");
//    	set2.add("童装蕙");
//    	set2.add("屠岸贾");
//    	set2.add("拓拔搅琬");
//    	set2.add("歪歪痘痘");
//    	set2.add("外婆的点心");
//    	set2.add("王灵裴");
//    	set2.add("唯我独尊");
//    	set2.add("维也纳の火");
//    	set2.add("蜗牛");
//    	set2.add("乌鸦");
//    	set2.add("无题");
//    	set2.add("无终窑矫");
//    	set2.add("吴君音");
//    	set2.add("午黯悍");
//    	set2.add("西郭羸霏");
//    	set2.add("西馗宛");
//    	set2.add("席列绵");
//    	set2.add("夏侯兼琸");
//    	set2.add("夏继鎏");
//    	set2.add("鲜于榭涧");
//    	set2.add("线葫风");
//    	set2.add("小丢垓");
//    	set2.add("小飞猪");
//    	set2.add("小手乱摸");
//    	set2.add("小五灬");
//    	set2.add("小薪~");
//    	set2.add("小星星");
//    	set2.add("小铱");
//    	set2.add("笑丶倾城");
//    	set2.add("邪情丶傲");
//    	set2.add("鈊葬灬宝贝");
//    	set2.add("鈊葬灬小龙");
//    	set2.add("轩辕绥纯");
//    	set2.add("玄殿壬");
//    	set2.add("雪后阳光1");
//    	set2.add("血煞小雷");
//    	set2.add("血影修罗");
//    	set2.add("牙牙");
//    	set2.add("闫宥非");
//    	set2.add("晏羽莉雾");
//    	set2.add("燕璨瑚");
//    	set2.add("燕沅妒");
//    	set2.add("妖狼");
//    	set2.add("爷爷");
//    	set2.add("业峨绿");
//    	set2.add("一帝");
//    	set2.add("一二三四");
//    	set2.add("一剑西来");
//    	set2.add("伊利早餐奶");
//    	set2.add("依然帅气");
//    	set2.add("忆旧容。");
//    	set2.add("易杖矫");
//    	set2.add("殷七跃");
//    	set2.add("银倏纯");
//    	set2.add("隐狐");
//    	set2.add("印材燕");
//    	set2.add("婴枫嫔");
//    	set2.add("雍旋夕");
//    	set2.add("永恒");
//    	set2.add("尤贝尔");
//    	set2.add("由听壮");
//    	set2.add("有霁沙");
//    	set2.add("鱼侣姥");
//    	set2.add("元始天尊");
//    	set2.add("袁寿瑰");
//    	set2.add("原始道尊");
//    	set2.add("原始天尊");
//    	set2.add("源渊岗");
//    	set2.add("悦风");
//    	set2.add("云绝笑");
//    	set2.add("战皇");
//    	set2.add("战社渥");
//    	set2.add("湛侑啸");
//    	set2.add("张简町妖");
//    	set2.add("张廖复涣");
//    	set2.add("张翩蔓");
//    	set2.add("招睦绎");
//    	set2.add("征冽阳");
//    	set2.add("郑粕凌");
//    	set2.add("直婚绣");
//    	set2.add("治谋彗");
//    	set2.add("掷眠皕");
//    	set2.add("终坚愉");
//    	set2.add("助纣为虐");
//    	set2.add("柱子哥");
//    	set2.add("邹换函");
//    	set2.add("醉红尘");
//    	set2.add("醉红牛");
//    	set2.add("醉枕丶妖娆");
//
//    	set2.removeAll(set);
//    	System.out.println("次日留存:" + (set2.size() + 0f) / set.size());
//    	System.out.println();
    }
}
